// Script local de seed — desabilita verificação TLS para funcionar atrás de proxy corporativo
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const SURL = 'https://fugztekwkpmambvcyrmm.supabase.co';
const SK = process.env.SUPABASE_SERVICE_ROLE;  // export SUPABASE_SERVICE_ROLE=seu_token
const PAT = process.env.SUPABASE_PAT;          // export SUPABASE_PAT=seu_token
const REF = 'fugztekwkpmambvcyrmm';
const H = {
  apikey: SK,
  Authorization: `Bearer ${SK}`,
  'Content-Type': 'application/json',
  Prefer: 'return=minimal',
};

async function doSQL(q) {
  const r = await fetch(`https://api.supabase.com/v1/projects/${REF}/database/query`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${PAT}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: q }),
  });
  const t = await r.text();
  if (!r.ok) throw new Error(`SQL ${r.status}: ${t}`);
  return t;
}

async function doREST(method, path, body) {
  const r = await fetch(`${SURL}/rest/v1/${path}`, {
    method,
    headers: H,
    body: body != null ? JSON.stringify(body) : undefined,
  });
  if (!r.ok) {
    const t = await r.text();
    throw new Error(`REST ${method} ${path} ${r.status}: ${t}`);
  }
}

// GIF URLs
const G = {
  sr: 'https://static.exercisedb.dev/media/EIeI8Vf.gif',
  si: 'https://static.exercisedb.dev/media/3TZduzM.gif',
  sd: 'https://static.exercisedb.dev/media/GrO65fd.gif',
  shd: 'https://static.exercisedb.dev/media/2vYapFl.gif',
  cru: 'https://static.exercisedb.dev/media/1PLE8e9.gif',
  co: 'https://static.exercisedb.dev/media/0CXGHya.gif',
  fl: 'https://static.exercisedb.dev/media/0V2YQjW.gif',
  dl: 'https://static.exercisedb.dev/media/ila4NZS.gif',
  pu: 'https://static.exercisedb.dev/media/3_9Ib4w.gif',
  lat: 'https://static.exercisedb.dev/media/LEprlgG.gif',
  rb: 'https://static.exercisedb.dev/media/eZyBC3j.gif',
  ru: 'https://static.exercisedb.dev/media/C0MA9bC.gif',
  rdb: 'https://static.exercisedb.dev/media/BJ0Hz5L.gif',
  rw: 'https://static.exercisedb.dev/media/A3P4O0R.gif',
  po: 'https://static.exercisedb.dev/media/0I0CmMl.gif',
  sq: 'https://static.exercisedb.dev/media/DhMl549.gif',
  hk: 'https://static.exercisedb.dev/media/5VCj6iH.gif',
  sm: 'https://static.exercisedb.dev/media/dzz6BiV.gif',
  bg: 'https://static.exercisedb.dev/media/jZi0Vj6.gif',
  lp: 'https://static.exercisedb.dev/media/10Z2DXU.gif',
  le: 'https://static.exercisedb.dev/media/my33uHU.gif',
  mf: 'https://static.exercisedb.dev/media/17lJ1kr.gif',
  st: 'https://static.exercisedb.dev/media/5eLRITT.gif',
  lu: 'https://static.exercisedb.dev/media/62Nw60O.gif',
  cf: 'https://static.exercisedb.dev/media/bJYHBIN.gif',
  cs: 'https://static.exercisedb.dev/media/D2f6GxR.gif',
  ht: 'https://static.exercisedb.dev/media/qKBpF7I.gif',
  db: 'https://static.exercisedb.dev/media/kTbSH9h.gif',
  dhd: 'https://static.exercisedb.dev/media/A6wtbuL.gif',
  ar: 'https://static.exercisedb.dev/media/Xy4jlWA.gif',
  el: 'https://static.exercisedb.dev/media/DsgkuIt.gif',
  ef: 'https://static.exercisedb.dev/media/3eGE2JC.gif',
  ra: 'https://static.exercisedb.dev/media/83HoW9X.gif',
  fp: 'https://static.exercisedb.dev/media/gAwDzB3.gif',
  ep: 'https://static.exercisedb.dev/media/3mNAkfB.gif',
  rcb: 'https://static.exercisedb.dev/media/25GPyDY.gif',
  rca: 'https://static.exercisedb.dev/media/Rn5zTiw.gif',
  rm: 'https://static.exercisedb.dev/media/2sQGZ5b.gif',
  rsc: 'https://static.exercisedb.dev/media/1V1gj1u.gif',
  rco: 'https://static.exercisedb.dev/media/dFRcMC5.gif',
  tp: 'https://static.exercisedb.dev/media/gAwDzB3.gif',
  tc: 'https://static.exercisedb.dev/media/VKIFPTK.gif',
  tf: 'https://static.exercisedb.dev/media/2IxROQ1.gif',
  tt: 'https://static.exercisedb.dev/media/1TVoin7.gif',
  tk: 'https://static.exercisedb.dev/media/3T12T87.gif',
  mb: 'https://static.exercisedb.dev/media/aWedzZX.gif',
  mp: 'https://static.exercisedb.dev/media/iqOdmMz.gif',
  ab: 'https://static.exercisedb.dev/media/8xUv4J7.gif',
  pr: 'https://static.exercisedb.dev/media/VBAWRPG.gif',
  ep2: 'https://static.exercisedb.dev/media/B2Uyrd7.gif',
  mc: 'https://static.exercisedb.dev/media/0MWdXj2.gif',
  abd: 'https://static.exercisedb.dev/media/CHpahtl.gif',
  pc: 'https://static.exercisedb.dev/media/1g5bPpA.gif',
  bu: 'https://static.exercisedb.dev/media/GvqfMDk.gif',
};

const EX = [
  // PEITO
  { name: 'Supino Reto com Barra', category: 'peito', primary_muscle: 'Peitoral Maior', secondary_muscles: ['Tríceps', 'Deltóide Anterior'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.sr, instructions: 'Deite no banco plano, segure a barra na largura dos ombros, desça ao peito e empurre.', steps: ['Deite no banco plano com os pés bem apoiados no chão.', 'Mãos na barra um pouco mais afastadas que os ombros, pegada pronada.', 'Retire a barra e desça de forma controlada até tocar levemente o peitoral.', 'Empurre a barra para cima de forma explosiva.', 'Expire ao subir e repita.'], form_tips: ['Ombros retraídos e deprimidos durante todo o exercício.', 'Pés totalmente apoiados no chão.', 'Mantenha um leve arco lombar natural.'], common_mistakes: ['Arquear excessivamente a lombar.', 'Descer a barra de forma descontrolada.', 'Cotovelos muito abertos (mais de 75°).'], variations: ['Supino Reto com Halteres', 'Supino Inclinado com Barra', 'Supino Declinado com Barra'], substitutes: ['Flexão de Braço', 'Cross Over', 'Crucifixo Reto'] },
  { name: 'Supino Inclinado com Barra', category: 'peito', primary_muscle: 'Peitoral Superior', secondary_muscles: ['Tríceps', 'Deltóide Anterior'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.si, instructions: 'Banco inclinado a 30-45°. Foco na parte superior do peitoral.', steps: ['Ajuste o banco a 30-45°.', 'Mãos na barra na largura dos ombros.', 'Desça de forma controlada em direção à clavícula.', 'Empurre de volta.'], form_tips: ['Inclinação de 30° é mais eficiente — acima de 45° transfere para o ombro.', 'Retraia as escápulas contra o banco.'], common_mistakes: ['Inclinação excessiva.', 'Descida rápida sem controle.'], variations: ['Supino Inclinado com Halteres', 'Crucifixo Inclinado'], substitutes: ['Supino Reto com Barra', 'Desenvolvimento com Halteres'] },
  { name: 'Supino Declinado com Barra', category: 'peito', primary_muscle: 'Peitoral Inferior', secondary_muscles: ['Tríceps'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.sd, instructions: 'Banco declinado. Enfatiza a porção inferior do peitoral.', steps: ['Ajuste o banco em declinação com pés presos.', 'Mãos na barra levemente mais abertas que os ombros.', 'Desça de forma controlada em direção ao abdômen superior.', 'Empurre de volta.'], form_tips: ['Mantenha a cabeça apoiada no banco.'], common_mistakes: ['Levantar a cabeça do banco.', 'Descer muito rápido.'], variations: ['Supino Declinado com Halteres', 'Mergulho nas Paralelas'], substitutes: ['Mergulho entre Bancos', 'Cross Over'] },
  { name: 'Supino Reto com Halteres', category: 'peito', primary_muscle: 'Peitoral Maior', secondary_muscles: ['Tríceps', 'Deltóide Anterior'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.shd, instructions: 'Maior amplitude de movimento que a barra.', steps: ['Sente no banco com halteres nas coxas.', 'Deite posicionando os halteres ao lado do peito.', 'Pressione para cima até quase se tocarem.', 'Desça de forma controlada.'], form_tips: ['Aproveite o alongamento controlado na descida.', 'Mantenha os pulsos neutros.'], common_mistakes: ['Deixar os halteres se tocarem no topo.', 'Descer demais.'], variations: ['Supino Inclinado com Halteres', 'Crucifixo Reto'], substitutes: ['Supino Reto com Barra', 'Flexão de Braço'] },
  { name: 'Supino Inclinado com Halteres', category: 'peito', primary_muscle: 'Peitoral Superior', secondary_muscles: ['Tríceps'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.si, instructions: 'Banco a 30-45°. Desça os halteres até a linha do peito.', steps: ['Ajuste o banco a 30-45°.', 'Deite com os halteres posicionados ao lado do peito.', 'Pressione para cima com leve convergência.', 'Desça de forma controlada.'], form_tips: ['Inclinação de 30° ativa mais peitoral superior.'], common_mistakes: ['Usar inclinação acima de 45°.'], variations: ['Supino Inclinado com Barra', 'Crucifixo Inclinado'], substitutes: ['Cross Over', 'Supino Reto com Halteres'] },
  { name: 'Crucifixo Reto', category: 'peito', primary_muscle: 'Peitoral Maior', secondary_muscles: ['Deltóide Anterior'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.cru, instructions: 'Deite no banco, abra os braços em arco até sentir o alongamento no peitoral.', steps: ['Deite no banco com halteres, braços estendidos acima do peito.', 'Com leve flexão no cotovelo, abra os braços em arco.', 'Desça até sentir um bom alongamento.', 'Contraia o peitoral e retorne em arco.'], form_tips: ['Mantenha leve flexão nos cotovelos.', 'Use cargas leves.'], common_mistakes: ['Fletir muito os cotovelos.', 'Descer demais os halteres.'], variations: ['Crucifixo Inclinado', 'Cross Over'], substitutes: ['Cross Over', 'Supino Reto com Halteres'] },
  { name: 'Crucifixo Inclinado', category: 'peito', primary_muscle: 'Peitoral Superior', secondary_muscles: ['Deltóide Anterior'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.cru, instructions: 'Banco inclinado. Isola melhor a parte superior do peitoral.', steps: ['Ajuste o banco a 30°.', 'Deite com halteres estendidos acima do peito.', 'Abra os braços em arco com leve flexão no cotovelo.', 'Retorne contraindo o peitoral superior.'], form_tips: ['Inclinação de 30° é ideal para o peitoral clavicular.'], common_mistakes: ['Inclinação acima de 45°.'], variations: ['Crucifixo Reto', 'Cross Over'], substitutes: ['Supino Inclinado com Halteres', 'Cross Over'] },
  { name: 'Cross Over', category: 'peito', primary_muscle: 'Peitoral Maior', secondary_muscles: ['Deltóide Anterior'], equipment: 'Cabo', difficulty: 'iniciante', animation_url: G.co, instructions: 'Puxe os cabos em arco frente ao corpo. Contraia o peitoral na posição final.', steps: ['Polias em posição alta, segure as alças com braços abertos.', 'Incline o tronco levemente para frente.', 'Puxe as alças em arco convergindo na frente do corpo.', 'Contraia o peitoral no ponto final e retorne.'], form_tips: ['Polias altas = peitoral inferior. Polias baixas = peitoral superior.', 'Cotovelos levemente flexionados.'], common_mistakes: ['Dobrar excessivamente os cotovelos.', 'Não contrair no ponto final.'], variations: ['Cross Over Baixo', 'Cross Over Médio'], substitutes: ['Crucifixo Reto', 'Pec Deck'] },
  { name: 'Flexão de Braço', category: 'peito', primary_muscle: 'Peitoral Maior', secondary_muscles: ['Tríceps', 'Deltóide Anterior'], equipment: 'Peso corporal', difficulty: 'iniciante', animation_url: G.fl, instructions: 'Mãos na largura dos ombros. Desça até o peito quase tocar o chão.', steps: ['Apoie as mãos no chão na largura dos ombros.', 'Estenda os braços e apoie os dedos dos pés em linha reta.', 'Contraia o abdômen e glúteos para estabilizar.', 'Desça de forma controlada até o peito quase tocar o chão.', 'Empurre de volta.'], form_tips: ['Mantenha o corpo completamente reto.', 'Pescoço neutro.'], common_mistakes: ['Quadril caindo ou subindo.', 'Não descer até a amplitude completa.', 'Cotovelos muito abertos.'], variations: ['Flexão Fechada', 'Flexão com Pés Elevados', 'Flexão Diamante'], substitutes: ['Supino Reto com Barra', 'Mergulho entre Bancos'] },
  { name: 'Flexão com Pés Elevados', category: 'peito', primary_muscle: 'Peitoral Superior', secondary_muscles: ['Tríceps'], equipment: 'Peso corporal', difficulty: 'intermediario', animation_url: G.fl, instructions: 'Pés elevados para maior ativação da parte superior do peitoral.', steps: ['Posicione os pés em um banco ou superfície elevada.', 'Apoie as mãos no chão na largura dos ombros.', 'Desça o peito de forma controlada.', 'Empurre de volta mantendo o corpo reto.'], form_tips: ['Quanto maior a elevação dos pés, maior a ativação do peitoral superior.'], common_mistakes: ['Deixar o quadril subir.'], variations: ['Flexão de Braço Padrão'], substitutes: ['Supino Inclinado com Barra', 'Crucifixo Inclinado'] },
  { name: 'Mergulho entre Bancos', category: 'peito', primary_muscle: 'Peitoral Inferior', secondary_muscles: ['Tríceps'], equipment: 'Peso corporal', difficulty: 'iniciante', animation_url: G.mb, instructions: 'Incline o corpo para frente para focar no peitoral inferior.', steps: ['Mãos em banco atrás, pés em banco à frente.', 'Incline o tronco levemente para frente.', 'Desça flexionando os cotovelos até os braços ficarem a 90°.', 'Empurre de volta.'], form_tips: ['Tronco inclinado = peitoral. Tronco ereto = tríceps.'], common_mistakes: ['Descer além de 90° nos cotovelos.'], variations: ['Mergulho nas Paralelas'], substitutes: ['Cross Over', 'Supino Declinado com Barra'] },
  // COSTAS
  { name: 'Levantamento Terra', category: 'costas', primary_muscle: 'Eretores da Espinha', secondary_muscles: ['Glúteos', 'Isquiotibiais', 'Trapézio'], equipment: 'Barra', difficulty: 'avancado', animation_url: G.dl, instructions: 'Pés na largura do quadril, barra sobre os pés. Empurre o chão e mantenha as costas retas.', steps: ['Pés na largura do quadril com a barra sobre a metade dos pés.', 'Pegada pronada ou mista, escápulas acima da barra, costas retas.', 'Inspire fundo, pressione o abdômen (Valsalva) e empurre o chão.', 'Mantenha a barra próxima ao corpo.', 'Na posição final, empurre os quadris para frente.'], form_tips: ['"Quebre o chão" com os pés antes de levantar.', 'Barra o mais próximo do corpo possível.', 'Olhe para frente e levemente para baixo.'], common_mistakes: ['Arredondar a lombar.', 'Joelhos colapsando para dentro.', 'Puxar com as costas em vez de empurrar com as pernas.'], variations: ['Levantamento Terra Sumô', 'Levantamento Terra Romeno', 'Levantamento Terra Unilateral'], substitutes: ['Remada Curvada com Barra', 'Stiff'] },
  { name: 'Barra Fixa', category: 'costas', primary_muscle: 'Grande Dorsal', secondary_muscles: ['Bíceps', 'Rombóides'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.pu, instructions: 'Pegada pronada, largura maior que os ombros. Puxe até o queixo ultrapassar a barra.', steps: ['Pegada pronada, mãos mais afastadas que os ombros.', 'Parta de braços completamente estendidos.', 'Retraia as escápulas e puxe os cotovelos em direção aos quadris.', 'Suba até o queixo ultrapassar a barra.', 'Desça de forma controlada.'], form_tips: ['Inicie retraindo as escápulas.', 'Evite balançar o corpo.'], common_mistakes: ['Não descer completamente.', 'Usar impulso do corpo.'], variations: ['Chin-up', 'Barra Fixa Neutra', 'Barra Fixa com Peso'], substitutes: ['Puxada Alta', 'Remada Curvada com Barra'] },
  { name: 'Puxada Alta', category: 'costas', primary_muscle: 'Grande Dorsal', secondary_muscles: ['Bíceps', 'Rombóides'], equipment: 'Máquina', difficulty: 'iniciante', animation_url: G.lat, instructions: 'Puxe a barra até a clavícula, cotovelos apontando para baixo.', steps: ['Coxas presas sob o suporte, pegada pronada mais afastada que os ombros.', 'Incline o tronco levemente para trás (15-20°).', 'Puxe a barra em direção à clavícula, guiando com os cotovelos.', 'Contraia o dorsal e retorne controlando.'], form_tips: ['Não puxe atrás da cabeça.', 'Foque em "puxar os cotovelos para baixo e para trás".'], common_mistakes: ['Puxar atrás da cabeça.', 'Usar impulso do tronco.'], variations: ['Puxada Fechada', 'Puxada Neutra', 'Puxada Supinada'], substitutes: ['Barra Fixa', 'Remada Curvada com Barra'] },
  { name: 'Puxada Neutra', category: 'costas', primary_muscle: 'Grande Dorsal', secondary_muscles: ['Bíceps'], equipment: 'Máquina', difficulty: 'iniciante', animation_url: G.lat, instructions: 'Pegada paralela. Menor estresse no ombro, boa opção para iniciantes.', steps: ['Use a barra V no cabo.', 'Sente com coxas presas e tronco levemente para trás.', 'Puxe a barra em direção ao peito com cotovelos para baixo.', 'Retorne controlando.'], form_tips: ['Pegada neutra é a mais amigável para os ombros.'], common_mistakes: ['Inclinar excessivamente o tronco.'], variations: ['Puxada Alta', 'Barra Fixa Neutra'], substitutes: ['Puxada Alta', 'Remada Unilateral com Halter'] },
  { name: 'Remada Curvada com Barra', category: 'costas', primary_muscle: 'Grande Dorsal', secondary_muscles: ['Rombóides', 'Trapézio', 'Bíceps'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.rb, instructions: 'Tronco a 45°, puxe a barra em direção ao umbigo. Mantenha as costas retas.', steps: ['Pegada pronada na largura dos ombros, tronco a 45° com coluna neutra.', 'Joelhos levemente flexionados.', 'Puxe a barra em direção ao umbigo.', 'Contraia as escápulas ao final.', 'Retorne de forma controlada.'], form_tips: ['Tronco mais horizontal = mais dorsal. Mais ereto = mais trapézio.', 'Não curve a lombar.'], common_mistakes: ['Arredondar as costas.', 'Usar impulso do quadril excessivo.', 'Puxar para o peito em vez do abdômen.'], variations: ['Remada com Halteres', 'Remada em T', 'Remada Unilateral com Halter'], substitutes: ['Puxada Alta', 'Remada Baixa no Cabo'] },
  { name: 'Remada Unilateral com Halter', category: 'costas', primary_muscle: 'Grande Dorsal', secondary_muscles: ['Rombóides', 'Bíceps'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.ru, instructions: 'Apoie um joelho no banco. Puxe o halter até o quadril.', steps: ['Apoie o joelho e a mão do mesmo lado no banco.', 'Segure o halter com braço estendido.', 'Puxe o halter em direção ao quadril com cotovelo para o teto.', 'Retraia completamente a escápula.', 'Retorne de forma controlada.'], form_tips: ['"Puxar o cotovelo para o teto" é a cue correta.', 'Não gire o quadril.'], common_mistakes: ['Rotacionar o quadril.', 'Não atingir a retração total da escápula.'], variations: ['Remada Curvada com Barra', 'Remada no Cabo Unilateral'], substitutes: ['Remada Curvada com Barra', 'Puxada Alta'] },
  { name: 'Remada Baixa no Cabo', category: 'costas', primary_muscle: 'Grande Dorsal', secondary_muscles: ['Rombóides', 'Trapézio'], equipment: 'Cabo', difficulty: 'iniciante', animation_url: G.rw, instructions: 'Puxe o cabo em direção ao abdômen, cotovelos próximos ao corpo.', steps: ['Sente com pés apoiados e joelhos levemente flexionados.', 'Segure a alça com braços estendidos e tronco levemente à frente.', 'Puxe a alça em direção ao umbigo com cotovelos próximos ao corpo.', 'Retraia as escápulas e retorne controlando.'], form_tips: ['Não balance o tronco para trás.'], common_mistakes: ['Usar o tronco como alavanca.', 'Arredondar as costas.'], variations: ['Remada com Barra de V', 'Remada com Corda'], substitutes: ['Remada Curvada com Barra', 'Remada Unilateral com Halter'] },
  { name: 'Remada com Halteres', category: 'costas', primary_muscle: 'Rombóides', secondary_muscles: ['Trapézio', 'Deltóide Posterior'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.rdb, instructions: 'Incline o tronco. Puxe os halteres em direção ao quadril.', steps: ['Segure dois halteres e incline o tronco a 45-90°.', 'Braços estendidos, costas neutras.', 'Puxe os halteres simultaneamente em direção ao quadril.', 'Contraia as escápulas e retorne.'], form_tips: ['Tronco mais horizontal = maior ativação do dorsal.'], common_mistakes: ['Não retrair as escápulas.'], variations: ['Remada Curvada Unilateral', 'Remada Curvada com Barra'], substitutes: ['Remada Unilateral com Halter', 'Puxada Alta'] },
  { name: 'Encolhimento com Barra', category: 'costas', primary_muscle: 'Trapézio', secondary_muscles: ['Deltóide'], equipment: 'Barra', difficulty: 'iniciante', animation_url: G.rb, instructions: 'Eleve os ombros em direção às orelhas. Não rode os ombros.', steps: ['Pegada pronada na largura dos ombros.', 'Eleve os ombros diretamente para cima.', 'Mantenha no topo por 1 segundo.', 'Desça de forma controlada.'], form_tips: ['Movimento estritamente vertical.'], common_mistakes: ['Rodar os ombros (movimento circular).'], variations: ['Encolhimento com Halteres', 'Encolhimento no Cabo'], substitutes: ['Remada Alta', 'Face Pull'] },
  { name: 'Pull Over', category: 'costas', primary_muscle: 'Grande Dorsal', secondary_muscles: ['Peitoral', 'Tríceps'], equipment: 'Halteres', difficulty: 'intermediario', animation_url: G.po, instructions: 'Deite no banco, segure um halter com as duas mãos e desça atrás da cabeça.', steps: ['Deite transversalmente com apenas as escápulas apoiadas no banco.', 'Segure um halter com as duas mãos acima do peito.', 'Com cotovelos levemente flexionados, desça o halter atrás da cabeça.', 'Retorne em arco contraindo o dorsal.'], form_tips: ['Quadril abaixo do nível do banco para maior amplitude.'], common_mistakes: ['Dobrar demais os cotovelos.'], variations: ['Pull Over no Cabo', 'Pull Over na Máquina'], substitutes: ['Puxada Alta', 'Remada Curvada com Barra'] },
  // PERNAS
  { name: 'Agachamento Livre', category: 'pernas', primary_muscle: 'Quadríceps', secondary_muscles: ['Glúteos', 'Isquiotibiais', 'Panturrilha'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.sq, instructions: 'Pés na largura dos ombros, desça até as coxas ficarem paralelas ao chão.', steps: ['Barra na parte posterior dos trapézios, pés na largura dos ombros, pontas levemente para fora.', 'Inspire fundo e pressione o abdômen.', 'Quebre nos quadris e joelhos simultaneamente.', 'Desça até as coxas ficarem paralelas ou abaixo do chão.', 'Empurre o chão com os pés para subir.'], form_tips: ['Joelhos acompanham a direção dos pés.', 'Peito erguido e coluna neutra.'], common_mistakes: ['Joelhos colapsando para dentro.', 'Subir apenas com as costas.', 'Elevar os calcanhares.'], variations: ['Agachamento Sumô', 'Agachamento Hack', 'Agachamento Búlgaro'], substitutes: ['Leg Press 45°', 'Cadeira Extensora', 'Afundo'] },
  { name: 'Agachamento Hack', category: 'pernas', primary_muscle: 'Quadríceps', secondary_muscles: ['Glúteos'], equipment: 'Máquina', difficulty: 'iniciante', animation_url: G.hk, instructions: 'Ênfase na parte frontal da coxa. Pés a 45° para proteger os joelhos.', steps: ['Costas apoiadas no encosto inclinado, pés na plataforma.', 'Destrave e desça controlando até 90° nos joelhos.', 'Empurre de volta sem travar os joelhos no topo.'], form_tips: ['Pés mais baixos = mais quadríceps. Pés mais altos = mais glúteos.'], common_mistakes: ['Levantar o calcanhar.', 'Descer apenas parcialmente.'], variations: ['Agachamento Livre', 'Leg Press 45°'], substitutes: ['Leg Press 45°', 'Cadeira Extensora'] },
  { name: 'Agachamento Sumô', category: 'pernas', primary_muscle: 'Quadríceps', secondary_muscles: ['Glúteos', 'Adutores'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.sm, instructions: 'Pés mais afastados, pontas voltadas para fora. Ativa mais o glúteo e adutor.', steps: ['Pés bem afastados, pontas a 45° para fora, barra nas costas.', 'Inspire e desça mantendo o tronco mais ereto.', 'Desça até as coxas ficarem paralelas.', 'Empurre de volta espalhando o chão.'], form_tips: ['Joelhos alinhados com os dedos dos pés.'], common_mistakes: ['Joelhos colapsando para dentro.', 'Inclinar excessivamente o tronco.'], variations: ['Agachamento Livre', 'Agachamento Goblet Sumô'], substitutes: ['Leg Press com Pés Afastados', 'Cadeira de Abdutora'] },
  { name: 'Agachamento Búlgaro', category: 'pernas', primary_muscle: 'Quadríceps', secondary_muscles: ['Glúteos', 'Isquiotibiais'], equipment: 'Halteres', difficulty: 'avancado', animation_url: G.bg, instructions: 'Pé traseiro elevado. Excelente para força unilateral.', steps: ['Peito do pé traseiro em um banco atrás.', 'Pé da frente a uma distância que permita 90° no joelho.', 'Segure halteres e desça em linha reta.', 'Desça até o joelho traseiro quase tocar o chão.', 'Empurre de volta com o pé da frente.'], form_tips: ['O tronco pode inclinar levemente para frente.'], common_mistakes: ['Pé da frente muito próximo.', 'Perder o equilíbrio.'], variations: ['Afundo', 'Passada'], substitutes: ['Afundo com Halteres', 'Leg Press Unilateral'] },
  { name: 'Leg Press 45°', category: 'pernas', primary_muscle: 'Quadríceps', secondary_muscles: ['Glúteos', 'Isquiotibiais'], equipment: 'Máquina', difficulty: 'iniciante', animation_url: G.lp, instructions: 'Pés na largura dos ombros. Desça até 90° nos joelhos.', steps: ['Costas e glúteos totalmente apoiados, pés na largura dos ombros.', 'Destrave e desça controlando até 90°.', 'Empurre de volta sem travar os joelhos no topo.'], form_tips: ['Não deixe os glúteos saírem do assento.', 'Pés mais altos = mais glúteos.'], common_mistakes: ['Joelhos colapsando.', 'Bloquear totalmente os joelhos no topo.'], variations: ['Leg Press com Pés Altos', 'Leg Press Unilateral'], substitutes: ['Agachamento Livre', 'Agachamento Hack'] },
  { name: 'Cadeira Extensora', category: 'pernas', primary_muscle: 'Quadríceps', secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante', animation_url: G.le, instructions: 'Isola o quadríceps. Faça contração no ponto final do movimento.', steps: ['Ajuste o banco para o joelho alinhado ao eixo da máquina.', 'Estenda as pernas até quase o bloqueio e contraia o quadríceps.', 'Retorne de forma controlada.'], form_tips: ['Pausa de 1 segundo no ponto de contração máxima.'], common_mistakes: ['Usar impulso do tronco.', 'Não controlar a descida.'], variations: ['Cadeira Extensora Unilateral'], substitutes: ['Agachamento Hack', 'Leg Press 45°'] },
  { name: 'Mesa Flexora', category: 'pernas', primary_muscle: 'Isquiotibiais', secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante', animation_url: G.mf, instructions: 'Curl de perna deitado. Foco nos isquiotibiais.', steps: ['Deite com o dorso dos tornozelos sob o cilindro, joelhos na borda do banco.', 'Flexione os joelhos trazendo o cilindro em direção aos glúteos.', 'Contraia no topo e retorne controlando.'], form_tips: ['Não levante os quadris do banco.'], common_mistakes: ['Levantar o quadril.'], variations: ['Cadeira Flexora', 'Stiff'], substitutes: ['Stiff', 'Cadeira Flexora'] },
  { name: 'Cadeira Flexora', category: 'pernas', primary_muscle: 'Isquiotibiais', secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante', animation_url: G.mf, instructions: 'Curl de perna sentado. Mais estresse no isquiotibial distal.', steps: ['Sente na máquina com o encosto ajustado.', 'Posicione os tornozelos sobre o cilindro.', 'Flexione os joelhos trazendo os calcanhares para baixo.', 'Retorne controlando o excêntrico.'], form_tips: ['Sentado, o isquiotibial fica em maior alongamento.'], common_mistakes: ['Velocidade excessiva na fase excêntrica.'], variations: ['Mesa Flexora', 'Nordic Curl'], substitutes: ['Mesa Flexora', 'Stiff'] },
  { name: 'Stiff', category: 'pernas', primary_muscle: 'Isquiotibiais', secondary_muscles: ['Glúteos', 'Eretores da Espinha'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.st, instructions: 'Pernas quase estendidas, desça a barra pela frente das pernas sentindo o alongamento.', steps: ['Segure a barra na largura do quadril, leve flexão nos joelhos.', 'Incline o tronco para frente mantendo a coluna neutra.', 'Desça a barra pela frente das pernas sentindo o alongamento.', 'Contraia glúteos e isquiotibiais para retornar.'], form_tips: ['O movimento é iniciado pelo quadril, não pelos joelhos.', 'Mantenha a coluna neutra.'], common_mistakes: ['Arredondar as costas.', 'Dobrar demais os joelhos.'], variations: ['Stiff com Halteres', 'Stiff Unilateral'], substitutes: ['Mesa Flexora', 'Levantamento Terra'] },
  { name: 'Afundo', category: 'pernas', primary_muscle: 'Quadríceps', secondary_muscles: ['Glúteos', 'Isquiotibiais'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.lu, instructions: 'Passo longo à frente, desça o joelho traseiro próximo ao chão.', steps: ['Fique em pé com halteres nas mãos.', 'Dê um passo longo à frente.', 'Desça o joelho traseiro em direção ao chão sem tocá-lo.', 'Joelho da frente sobre o tornozelo.', 'Empurre de volta e alterne.'], form_tips: ['Mantenha o tronco ereto.'], common_mistakes: ['Joelho da frente ultrapassando muito a ponta do pé.', 'Passo muito curto.'], variations: ['Afundo Caminhando', 'Agachamento Búlgaro'], substitutes: ['Agachamento Livre', 'Leg Press 45°'] },
  { name: 'Panturrilha em Pé', category: 'pernas', primary_muscle: 'Panturrilha', secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante', animation_url: G.cf, instructions: 'Suba na ponta dos pés com amplitude completa. Faça a contração no topo.', steps: ['Ombros sob os apoios da máquina, pés na borda da plataforma.', 'Desça os calcanhares para baixo para alongar.', 'Suba na ponta dos pés o mais alto possível e contraia.', 'Retorne controlando a descida.'], form_tips: ['Amplitude completa é crucial.', 'Pausa de 1 segundo no topo e na descida.'], common_mistakes: ['Movimento parcial.', 'Velocidade excessiva.'], variations: ['Panturrilha Sentado', 'Panturrilha no Leg Press'], substitutes: ['Panturrilha Sentado'] },
  { name: 'Panturrilha Sentado', category: 'pernas', primary_muscle: 'Panturrilha', secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante', animation_url: G.cs, instructions: 'Foca no músculo sóleo. Importante para o volume total da panturrilha.', steps: ['Sente na máquina com joelhos a 90° sob o apoio.', 'Pés na borda da plataforma.', 'Desça os calcanhares e suba na ponta dos pés em amplitude completa.'], form_tips: ['O sóleo só é ativado com o joelho flexionado.'], common_mistakes: ['Não usar amplitude completa.'], variations: ['Panturrilha em Pé'], substitutes: ['Panturrilha em Pé'] },
  // OMBROS
  { name: 'Desenvolvimento Militar com Barra', category: 'ombros', primary_muscle: 'Deltóide Anterior', secondary_muscles: ['Deltóide Medial', 'Tríceps', 'Trapézio'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.db, instructions: 'Empurre a barra acima da cabeça. Pode ser feito em pé ou sentado.', steps: ['Barra na largura dos ombros, cotovelos à frente, barra na altura dos ombros.', 'Empurre diretamente para cima até os braços ficarem estendidos.', 'Desça de forma controlada até os ombros.'], form_tips: ['Em pé ativa mais o core; sentado permite maior carga.'], common_mistakes: ['Arquear excessivamente a lombar.'], variations: ['Desenvolvimento com Halteres', 'Desenvolvimento Arnold', 'Push Press'], substitutes: ['Desenvolvimento com Halteres', 'Elevação Lateral'] },
  { name: 'Desenvolvimento com Halteres', category: 'ombros', primary_muscle: 'Deltóide Anterior', secondary_muscles: ['Deltóide Medial', 'Tríceps'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.dhd, instructions: 'Maior amplitude que com barra. Cotovelos a 90° na posição inicial.', steps: ['Sente em banco com encosto ou fique em pé.', 'Halteres na altura dos ombros, cotovelos a 90°.', 'Empurre para cima com leve convergência.', 'Retorne controlando a descida.'], form_tips: ['Permite maior amplitude e estabilização.'], common_mistakes: ['Inclinar o tronco para trás excessivamente.'], variations: ['Desenvolvimento Arnold', 'Desenvolvimento Militar'], substitutes: ['Desenvolvimento com Barra', 'Elevação Lateral'] },
  { name: 'Desenvolvimento Arnold', category: 'ombros', primary_muscle: 'Deltóide Anterior', secondary_muscles: ['Deltóide Medial', 'Tríceps'], equipment: 'Halteres', difficulty: 'intermediario', animation_url: G.ar, instructions: 'Inicie com palmas viradas para você e gire durante o movimento.', steps: ['Halteres na frente do rosto, palmas voltadas para você.', 'Ao empurrar para cima, gire os pulsos para fora.', 'No topo, palmas voltadas para frente.', 'Retorne revertendo a rotação.'], form_tips: ['O movimento de rotação ativa os três feixes do deltóide.'], common_mistakes: ['Fazer a rotação muito rápida.'], variations: ['Desenvolvimento com Halteres', 'Desenvolvimento com Barra'], substitutes: ['Desenvolvimento com Halteres'] },
  { name: 'Elevação Lateral', category: 'ombros', primary_muscle: 'Deltóide Medial', secondary_muscles: [], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.el, instructions: 'Eleve os braços lateralmente até a altura dos ombros.', steps: ['Fique em pé com halteres ao lado do corpo.', 'Com leve flexão nos cotovelos, eleve os braços lateralmente.', 'Pare quando os braços estiverem paralelos ao chão.', 'Desça de forma controlada.'], form_tips: ['Polegar levemente para baixo no topo para maior ativação.', 'Use cargas leves.'], common_mistakes: ['Levantar acima dos ombros.', 'Usar impulso do corpo.'], variations: ['Elevação Lateral no Cabo', 'Elevação Lateral Inclinada'], substitutes: ['Face Pull', 'Desenvolvimento com Halteres'] },
  { name: 'Elevação Frontal', category: 'ombros', primary_muscle: 'Deltóide Anterior', secondary_muscles: [], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.ef, instructions: 'Eleve os braços à frente até a altura dos ombros. Controle a descida.', steps: ['Fique em pé com halteres na frente das coxas.', 'Eleve um braço (ou ambos) à frente até a altura dos ombros.', 'Retorne de forma controlada.'], form_tips: ['Mantenha o tronco estável.'], common_mistakes: ['Usar impulso do tronco.', 'Subir acima da linha dos ombros.'], variations: ['Elevação Frontal com Barra', 'Elevação Frontal no Cabo'], substitutes: ['Elevação Lateral', 'Desenvolvimento com Halteres'] },
  { name: 'Remada Alta', category: 'ombros', primary_muscle: 'Deltóide Medial', secondary_muscles: ['Trapézio', 'Bíceps'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.ra, instructions: 'Puxe a barra até a altura do queixo, cotovelos acima da barra.', steps: ['Pegada pronada na largura dos ombros.', 'Puxe a barra verticalmente até a altura do queixo.', 'Cotovelos acima da barra no topo.', 'Retorne de forma controlada.'], form_tips: ['Pegada mais aberta reduz risco de impingimento.'], common_mistakes: ['Pegada muito fechada.'], variations: ['Remada Alta com Halteres', 'Remada Alta no Cabo'], substitutes: ['Elevação Lateral', 'Face Pull'] },
  { name: 'Face Pull', category: 'ombros', primary_muscle: 'Deltóide Posterior', secondary_muscles: ['Rombóides', 'Trapézio'], equipment: 'Cabo', difficulty: 'iniciante', animation_url: G.fp, instructions: 'Puxe o cabo em direção ao rosto, cotovelos elevados. Rotação externa no final.', steps: ['Polia na altura dos olhos com a corda.', 'Dê um passo para trás e incline levemente o corpo.', 'Puxe a corda em direção ao rosto, separando as mãos ao chegar.', 'Cotovelos na altura dos ombros ou acima.', 'Faça a rotação externa no ponto final.'], form_tips: ['Excelente exercício para saúde do ombro.', 'Foque na rotação externa.'], common_mistakes: ['Cotovelos abaixo da linha dos ombros.', 'Não fazer a rotação externa.'], variations: ['Face Pull com Elástico', 'Voador Invertido com Halteres'], substitutes: ['Elevação Posterior com Halteres', 'Remada Alta'] },
  { name: 'Elevação Posterior com Halteres', category: 'ombros', primary_muscle: 'Deltóide Posterior', secondary_muscles: ['Rombóides'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.ep, instructions: 'Incline o tronco a 90°, eleve os halteres lateralmente.', steps: ['Sente na borda de um banco e incline o tronco até ficar paralelo ao chão.', 'Halteres com leve flexão nos cotovelos.', 'Eleve os halteres lateralmente até os braços ficarem paralelos ao chão.', 'Retorne de forma controlada.'], form_tips: ['Mantenha o tronco paralelo ao chão.'], common_mistakes: ['Levantar o tronco para usar impulso.'], variations: ['Face Pull', 'Voador Invertido na Máquina'], substitutes: ['Face Pull', 'Remada Alta'] },
  // BÍCEPS
  { name: 'Rosca Direta com Barra', category: 'biceps', primary_muscle: 'Bíceps Braquial', secondary_muscles: ['Braquial'], equipment: 'Barra', difficulty: 'iniciante', animation_url: G.rcb, instructions: 'Cotovelos fixos ao longo do corpo. Curl completo sem balançar o tronco.', steps: ['Pegada supinada na largura dos ombros, cotovelos fixos ao lado do corpo.', 'Flexione os cotovelos trazendo a barra em direção ao peito.', 'Contraia o bíceps no topo e retorne de forma controlada.'], form_tips: ['Os cotovelos são o eixo do movimento.'], common_mistakes: ['Balançar o tronco.', 'Cotovelos se afastando do corpo.'], variations: ['Rosca com EZ Bar', 'Rosca Alternada com Halteres'], substitutes: ['Rosca Alternada com Halteres', 'Rosca no Cabo'] },
  { name: 'Rosca Alternada com Halteres', category: 'biceps', primary_muscle: 'Bíceps Braquial', secondary_muscles: ['Braquial'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.rca, instructions: 'Um braço de cada vez, supinando o pulso durante o movimento.', steps: ['Fique em pé com halteres ao lado do corpo, palmas para dentro.', 'Flexione um cotovelo trazendo o halter ao ombro.', 'Gire o pulso para cima (supinação) durante a subida.', 'Retorne e repita com o outro braço.'], form_tips: ['A supinação do pulso maximiza a ativação do bíceps.'], common_mistakes: ['Não supinar o pulso.', 'Balançar o tronco.'], variations: ['Rosca Direta com Barra', 'Rosca Martelo'], substitutes: ['Rosca Direta com Barra', 'Rosca no Cabo'] },
  { name: 'Rosca Martelo', category: 'biceps', primary_muscle: 'Braquial', secondary_muscles: ['Bíceps Braquial'], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.rm, instructions: 'Pegada neutra (polegar para cima). Ativa mais o braquial e antebraço.', steps: ['Segure halteres com pegada neutra.', 'Flexione os cotovelos alternadamente ou simultaneamente.', 'Mantenha a pegada neutra durante todo o movimento.', 'Retorne de forma controlada.'], form_tips: ['A pegada neutra ativa o braquial, que fica sob o bíceps.'], common_mistakes: ['Girar o pulso para supinado.'], variations: ['Rosca Corda no Cabo', 'Rosca Cross Body'], substitutes: ['Rosca Alternada com Halteres', 'Rosca Direta com Barra'] },
  { name: 'Rosca Scott', category: 'biceps', primary_muscle: 'Bíceps Braquial', secondary_muscles: [], equipment: 'Barra/Halteres', difficulty: 'iniciante', animation_url: G.rsc, instructions: 'Apoio do braço no banco Scott. Isola o bíceps eliminando trapaça.', steps: ['Ajuste o banco Scott à altura das axilas.', 'Tríceps no apoio inclinado, segure a barra EZ com pegada supinada.', 'Flexione os cotovelos contraindo o bíceps.', 'Retorne de forma controlada até o alongamento completo.'], form_tips: ['Não trave os cotovelos no final.'], common_mistakes: ['Levantar o tríceps do suporte.'], variations: ['Rosca Concentrada', 'Rosca Direta com Barra'], substitutes: ['Rosca Concentrada', 'Rosca no Cabo'] },
  { name: 'Rosca Concentrada', category: 'biceps', primary_muscle: 'Bíceps Braquial', secondary_muscles: [], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.rsc, instructions: 'Cotovelo apoiado na coxa. Máximo isolamento do bíceps.', steps: ['Sente no banco com pernas abertas.', 'Apoie a parte de trás do cotovelo na parte interna da coxa.', 'Flexione o cotovelo em direção ao ombro.', 'Retorne de forma controlada.'], form_tips: ['A posição elimina qualquer compensação.'], common_mistakes: ['Inclinar o tronco para ajudar.'], variations: ['Rosca Scott', 'Rosca no Cabo'], substitutes: ['Rosca Scott', 'Rosca Direta com Barra'] },
  { name: 'Rosca Inclinada', category: 'biceps', primary_muscle: 'Bíceps Braquial', secondary_muscles: [], equipment: 'Halteres', difficulty: 'intermediario', animation_url: G.rcb, instructions: 'Banco inclinado. Alongamento máximo do bíceps no ponto inferior.', steps: ['Ajuste o banco a 45-60°.', 'Deite com os braços pendendo perpendicularmente ao chão.', 'Flexione os cotovelos trazendo os halteres ao ombro.', 'Retorne lentamente aproveitando o alongamento.'], form_tips: ['Força maior pré-alongamento do bíceps.'], common_mistakes: ['Trazer os cotovelos para frente.'], variations: ['Rosca Alternada com Halteres'], substitutes: ['Rosca Concentrada', 'Rosca no Cabo'] },
  { name: 'Rosca no Cabo', category: 'biceps', primary_muscle: 'Bíceps Braquial', secondary_muscles: [], equipment: 'Cabo', difficulty: 'iniciante', animation_url: G.rco, instructions: 'Tensão constante ao longo do movimento. Ótimo para finalização.', steps: ['Polia baixa com barra reta ou EZ.', 'Pegada supinada, cotovelos ao lado do corpo.', 'Flexione os cotovelos trazendo a barra ao peito.', 'Retorne controlando o excêntrico.'], form_tips: ['Cabo mantém tensão constante.'], common_mistakes: ['Afastar os cotovelos do corpo.'], variations: ['Rosca no Cabo Unilateral', 'Rosca Martelo no Cabo'], substitutes: ['Rosca Direta com Barra', 'Rosca Alternada com Halteres'] },
  // TRÍCEPS
  { name: 'Tríceps Pulley', category: 'triceps', primary_muscle: 'Tríceps Braquial', secondary_muscles: [], equipment: 'Cabo', difficulty: 'iniciante', animation_url: G.tp, instructions: 'Cotovelos fixos ao lado do corpo. Estenda completamente os braços.', steps: ['Polia alta com barra reta ou V, pegada pronada, cotovelos próximos ao corpo.', 'Estenda os cotovelos empurrando a barra para baixo.', 'Contraia o tríceps no ponto final e retorne controlando.'], form_tips: ['Os cotovelos são o eixo.'], common_mistakes: ['Cotovelos se afastando do corpo.', 'Inclinar o tronco.'], variations: ['Tríceps Corda no Cabo', 'Tríceps com Barra V'], substitutes: ['Tríceps Francês', 'Tríceps Testa'] },
  { name: 'Tríceps Corda no Cabo', category: 'triceps', primary_muscle: 'Tríceps Braquial', secondary_muscles: [], equipment: 'Cabo', difficulty: 'iniciante', animation_url: G.tc, instructions: 'Abra a corda no final do movimento para maior amplitude.', steps: ['Polia alta com corda dupla, cotovelos próximos ao corpo.', 'Empurre para baixo e separe os lados da corda no ponto final.', 'Retorne controlando o excêntrico.'], form_tips: ['Separar a corda no final aumenta a contração da cabeça lateral.'], common_mistakes: ['Não separar a corda.'], variations: ['Tríceps Pulley', 'Tríceps Overhead com Corda'], substitutes: ['Tríceps Pulley', 'Tríceps Testa'] },
  { name: 'Tríceps Francês', category: 'triceps', primary_muscle: 'Tríceps Braquial', secondary_muscles: [], equipment: 'Halteres/Barra', difficulty: 'intermediario', animation_url: G.tf, instructions: 'Deite ou sente. Desça o peso atrás da cabeça, cotovelos apontando para cima.', steps: ['Deite no banco com halter acima, cotovelos apontando para cima, fixos.', 'Desça o peso atrás da cabeça flexionando os cotovelos.', 'Estenda de volta.'], form_tips: ['Cotovelos apontando para o teto durante todo o movimento.'], common_mistakes: ['Cotovelos se abrindo.'], variations: ['Tríceps Testa', 'Tríceps Overhead no Cabo'], substitutes: ['Tríceps Testa', 'Tríceps Pulley'] },
  { name: 'Tríceps Testa', category: 'triceps', primary_muscle: 'Tríceps Braquial', secondary_muscles: [], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.tt, instructions: 'Deite no banco. Desça a barra em direção à testa com cotovelos fixos.', steps: ['Deite no banco com barra EZ acima do peito.', 'Cotovelos a 90° do tronco, apontando para cima.', 'Desça a barra em direção à testa.', 'Estenda os cotovelos voltando.'], form_tips: ['Barra EZ é mais confortável para os pulsos.'], common_mistakes: ['Cotovelos se movendo para fora.'], variations: ['Tríceps Francês', 'Tríceps Testa no Cabo'], substitutes: ['Tríceps Francês', 'Tríceps Pulley'] },
  { name: 'Tríceps Coice', category: 'triceps', primary_muscle: 'Tríceps Braquial', secondary_muscles: [], equipment: 'Halteres', difficulty: 'iniciante', animation_url: G.tk, instructions: 'Incline o tronco, cotovelo fixo. Estenda o braço para trás.', steps: ['Incline o tronco a 45°.', 'Cotovelo flexionado a 90°, junto ao corpo.', 'Estenda o cotovelo para trás até o braço ficar paralelo ao chão.', 'Contraia o tríceps e retorne.'], form_tips: ['Mantenha o cotovelo bem próximo ao corpo.'], common_mistakes: ['Cotovelo caindo.'], variations: ['Tríceps Coice no Cabo'], substitutes: ['Tríceps Pulley', 'Tríceps Corda no Cabo'] },
  { name: 'Mergulho no Banco', category: 'triceps', primary_muscle: 'Tríceps Braquial', secondary_muscles: ['Peitoral Inferior'], equipment: 'Peso corporal', difficulty: 'iniciante', animation_url: G.mb, instructions: 'Mãos no banco atrás, pernas estendidas. Desça flexionando os cotovelos.', steps: ['Mãos no banco com dedos apontando para frente, pernas estendidas.', 'Desça flexionando os cotovelos até os braços ficarem a 90°.', 'Empurre de volta.'], form_tips: ['Tronco próximo ao banco para focar no tríceps.'], common_mistakes: ['Descer além de 90°.'], variations: ['Mergulho nas Paralelas', 'Mergulho com Peso'], substitutes: ['Tríceps Pulley', 'Tríceps Testa'] },
  { name: 'Mergulho nas Paralelas', category: 'triceps', primary_muscle: 'Tríceps Braquial', secondary_muscles: ['Peitoral'], equipment: 'Peso corporal', difficulty: 'intermediario', animation_url: G.mp, instructions: 'Tronco ereto para focar no tríceps. Cotovelos próximos ao corpo.', steps: ['Segure as paralelas e suspenda o corpo.', 'Tronco o mais ereto possível.', 'Desça até os braços ficarem a 90°.', 'Empurre de volta.'], form_tips: ['Tronco ereto = tríceps. Tronco inclinado = peitoral.'], common_mistakes: ['Descer excessivamente.'], variations: ['Mergulho com Peso', 'Mergulho no Banco'], substitutes: ['Tríceps Testa', 'Tríceps Pulley'] },
  // ABDÔMEN
  { name: 'Abdominal Supra', category: 'abdomen', primary_muscle: 'Reto Abdominal', secondary_muscles: ['Oblíquos'], equipment: 'Peso corporal', difficulty: 'iniciante', animation_url: G.ab, instructions: 'Deite, joelhos flexionados. Suba apenas o suficiente para as escápulas saírem do chão.', steps: ['Deite de costas com joelhos flexionados e pés no chão.', 'Mãos atrás da cabeça sem entrelaçar os dedos.', 'Expire e contraia o abdômen, elevando as escápulas do chão.', 'Inspire e retorne lentamente.'], form_tips: ['Não puxe o pescoço com as mãos.', 'O movimento é curto.'], common_mistakes: ['Puxar o pescoço.', 'Usar impulso.'], variations: ['Abdominal com Rotação', 'Abdominal no Cabo', 'Crunch Reverso'], substitutes: ['Prancha Abdominal', 'Abdominal no Cabo'] },
  { name: 'Abdominal Infra', category: 'abdomen', primary_muscle: 'Reto Abdominal Inferior', secondary_muscles: [], equipment: 'Peso corporal', difficulty: 'iniciante', animation_url: G.ep2, instructions: 'Deite. Eleve os joelhos em direção ao peito controlando o movimento.', steps: ['Deite de costas com braços ao lado do corpo.', 'Eleve as pernas até ficarem perpendiculares ao chão.', 'Contraia o abdômen e retorne lentamente.'], form_tips: ['Não use impulso.'], common_mistakes: ['Costas arquearem durante a descida.'], variations: ['Elevação de Pernas'], substitutes: ['Abdominal Supra', 'Prancha Abdominal'] },
  { name: 'Prancha Abdominal', category: 'abdomen', primary_muscle: 'Core', secondary_muscles: ['Oblíquos', 'Glúteos'], equipment: 'Peso corporal', difficulty: 'iniciante', animation_url: G.pr, instructions: 'Apoio nos cotovelos e pés. Mantenha o corpo reto. Respire normalmente.', steps: ['Cotovelos no chão abaixo dos ombros, pontas dos pés apoiadas.', 'Contraia abdômen, glúteos e quadríceps.', 'Mantenha o corpo em linha reta.', 'Respire normalmente pelo tempo desejado.'], form_tips: ['Imagine que está empurrando o chão com os cotovelos.'], common_mistakes: ['Quadril caindo.', 'Quadril subindo demais.', 'Prender a respiração.'], variations: ['Prancha Lateral', 'Prancha com Pés Elevados'], substitutes: ['Abdominal Supra', 'Mountain Climber'] },
  { name: 'Prancha Lateral', category: 'abdomen', primary_muscle: 'Oblíquos', secondary_muscles: ['Core'], equipment: 'Peso corporal', difficulty: 'intermediario', animation_url: G.pr, instructions: 'Apoio em um cotovelo e pé. Quadril elevado formando linha reta.', steps: ['Deite de lado e apoie o cotovelo abaixo do ombro.', 'Eleve o quadril formando uma linha reta.', 'Mantenha a posição pelo tempo desejado.'], form_tips: ['Não deixe o quadril cair ou rotar.'], common_mistakes: ['Quadril caindo.'], variations: ['Prancha Lateral com Elevação de Quadril'], substitutes: ['Prancha Abdominal', 'Abdominal com Rotação'] },
  { name: 'Abdominal com Rotação', category: 'abdomen', primary_muscle: 'Oblíquos', secondary_muscles: ['Reto Abdominal'], equipment: 'Peso corporal', difficulty: 'iniciante', animation_url: G.ab, instructions: 'Suba e gire o tronco alternando os lados.', steps: ['Deite com joelhos flexionados, mãos atrás da cabeça.', 'Ao subir, gire o tronco levando o cotovelo direito ao joelho esquerdo.', 'Alterne os lados de forma controlada.'], form_tips: ['A rotação vem do tronco, não do pescoço.'], common_mistakes: ['Puxar o pescoço.', 'Rotacionar apenas o cotovelo.'], variations: ['Russian Twist', 'Abdominal Supra'], substitutes: ['Prancha Lateral', 'Russian Twist'] },
  { name: 'Elevação de Pernas', category: 'abdomen', primary_muscle: 'Reto Abdominal Inferior', secondary_muscles: [], equipment: 'Peso corporal', difficulty: 'intermediario', animation_url: G.ep2, instructions: 'Deite, pernas estendidas. Eleve até 90° e desça controlando.', steps: ['Deite com braços ao lado do corpo, pernas estendidas e unidas.', 'Eleve as pernas até 90°.', 'Desça lentamente sem tocar o chão.'], form_tips: ['Quanto mais lenta a descida, maior o trabalho.'], common_mistakes: ['Lombar sair do chão.'], variations: ['Elevação de Pernas na Barra'], substitutes: ['Abdominal Infra', 'Prancha Abdominal'] },
  { name: 'Abdominal no Cabo', category: 'abdomen', primary_muscle: 'Reto Abdominal', secondary_muscles: [], equipment: 'Cabo', difficulty: 'iniciante', animation_url: G.ab, instructions: 'Ajoelhe-se de costas para o cabo. Flexione o tronco contraindo o abdômen.', steps: ['Polia alta com corda, ajoelhe-se de frente para a máquina.', 'Segure a corda atrás da cabeça.', 'Flexione o tronco em direção ao chão contraindo o abdômen.', 'Retorne controlando.'], form_tips: ['O movimento vem do abdômen, não dos quadris.'], common_mistakes: ['Puxar com os braços.'], variations: ['Abdominal Supra'], substitutes: ['Abdominal Supra', 'Prancha Abdominal'] },
  { name: 'Mountain Climber', category: 'abdomen', primary_muscle: 'Core', secondary_muscles: ['Oblíquos', 'Quadríceps'], equipment: 'Peso corporal', difficulty: 'intermediario', animation_url: G.mc, instructions: 'Posição de flexão. Alterne puxando os joelhos em direção ao peito rapidamente.', steps: ['Posição de flexão com braços estendidos.', 'Puxe o joelho direito em direção ao peito.', 'Retorne e puxe o joelho esquerdo.', 'Alterne em ritmo rápido.'], form_tips: ['Mantenha o quadril baixo.'], common_mistakes: ['Quadril elevado.'], variations: ['Mountain Climber Lento', 'Mountain Climber Diagonal'], substitutes: ['Prancha Abdominal', 'Burpee'] },
  // GLÚTEOS
  { name: 'Hip Thrust com Barra', category: 'gluteos', primary_muscle: 'Glúteo Máximo', secondary_muscles: ['Isquiotibiais', 'Core'], equipment: 'Barra', difficulty: 'intermediario', animation_url: G.ht, instructions: 'Costas apoiadas no banco, barra no quadril. Empurre o quadril para cima contraindo o glúteo.', steps: ['Sente no chão com as costas na borda de um banco.', 'Barra no dobramento do quadril com proteção, pés na largura dos ombros.', 'Empurre o quadril para cima até o corpo ficar paralelo ao chão.', 'Contraia o glúteo com força no topo por 1 segundo.', 'Retorne de forma controlada.'], form_tips: ['No topo, tronco e coxas formam uma linha reta.', 'Empurre os joelhos para fora.'], common_mistakes: ['Hiperextender a lombar no topo.', 'Pés mal posicionados.'], variations: ['Hip Thrust Unilateral', 'Elevação Pélvica'], substitutes: ['Elevação Pélvica', 'Agachamento Sumô'] },
  { name: 'Elevação Pélvica', category: 'gluteos', primary_muscle: 'Glúteo Máximo', secondary_muscles: ['Isquiotibiais'], equipment: 'Peso corporal', difficulty: 'iniciante', animation_url: G.ht, instructions: 'Deite, joelhos flexionados. Eleve o quadril contraindo o glúteo no topo.', steps: ['Deite de costas com joelhos flexionados e pés no chão.', 'Eleve o quadril contraindo o glúteo até o corpo formar uma linha reta.', 'Retorne lentamente.'], form_tips: ['Ative o glúteo antes de iniciar o movimento.'], common_mistakes: ['Não contrair o glúteo no topo.'], variations: ['Hip Thrust com Barra', 'Elevação Pélvica Unilateral'], substitutes: ['Hip Thrust com Barra', 'Agachamento Sumô'] },
  { name: 'Cadeira de Abdutora', category: 'gluteos', primary_muscle: 'Glúteo Médio', secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante', animation_url: G.abd, instructions: 'Abra as pernas contra a resistência. Foco no glúteo médio e lateral.', steps: ['Sente na máquina com as pernas contra os apoios internos.', 'Abra as pernas contra a resistência até a amplitude máxima confortável.', 'Contraia o glúteo médio e retorne de forma controlada.'], form_tips: ['Pausa de 1 segundo no ponto de maior abertura.'], common_mistakes: ['Não controlar a fase de retorno.'], variations: ['Abdução com Elástico', 'Elevação Lateral de Perna'], substitutes: ['Agachamento Sumô', 'Hip Thrust com Barra'] },
  { name: 'Elevação de Quadril Unilateral', category: 'gluteos', primary_muscle: 'Glúteo Máximo', secondary_muscles: ['Core'], equipment: 'Peso corporal', difficulty: 'intermediario', animation_url: G.ht, instructions: 'Uma perna de cada vez. Maior ativação e desequilíbrio muscular corrigido.', steps: ['Deite de costas com um joelho flexionado e o outro estendido.', 'Eleve o quadril usando apenas a perna apoiada.', 'Mantenha a perna estendida paralela à outra.'], form_tips: ['Excelente para corrigir desequilíbrios entre os dois glúteos.'], common_mistakes: ['Rotacionar o quadril para compensar.'], variations: ['Hip Thrust Unilateral com Barra'], substitutes: ['Elevação Pélvica', 'Hip Thrust com Barra'] },
  { name: 'Agachamento com Faixa Elástica', category: 'gluteos', primary_muscle: 'Glúteo Máximo', secondary_muscles: ['Quadríceps', 'Glúteo Médio'], equipment: 'Faixa Elástica', difficulty: 'iniciante', animation_url: G.sq, instructions: 'Faixa acima dos joelhos. Empurre os joelhos para fora durante o agachamento.', steps: ['Faixa elástica logo acima dos joelhos.', 'Pés na largura dos ombros.', 'Empurre os joelhos para fora contra a resistência da faixa ao descer.', 'Mantenha a pressão na faixa.'], form_tips: ['A faixa obriga ativação contínua do glúteo médio.'], common_mistakes: ['Deixar os joelhos colapsarem.'], variations: ['Agachamento Livre', 'Hip Thrust com Faixa'], substitutes: ['Cadeira de Abdutora', 'Agachamento Sumô'] },
  { name: 'Stiff Unilateral', category: 'gluteos', primary_muscle: 'Glúteo Máximo', secondary_muscles: ['Isquiotibiais'], equipment: 'Halteres', difficulty: 'intermediario', animation_url: G.st, instructions: 'Uma perna de cada vez. Inclina o tronco enquanto eleva a perna traseira.', steps: ['Fique em pé com um halter na mão oposta ao lado de apoio.', 'Incline o tronco para frente elevando a perna traseira.', 'Coluna neutra e perna de apoio levemente flexionada.', 'Retorne à posição inicial.'], form_tips: ['"Empurrar o calcanhar para o teto" é a cue correta.'], common_mistakes: ['Deixar o quadril girar.'], variations: ['Stiff com Barra'], substitutes: ['Stiff', 'Hip Thrust com Barra'] },
  { name: 'Kick Back no Cabo', category: 'gluteos', primary_muscle: 'Glúteo Máximo', secondary_muscles: [], equipment: 'Cabo', difficulty: 'iniciante', animation_url: G.fp, instructions: 'De frente para o cabo, empurre a perna para trás contraindo o glúteo.', steps: ['Cabo no tornozelo na polia baixa.', 'Segure a máquina para apoio, levemente inclinado.', 'Empurre a perna para trás com joelho levemente flexionado.', 'Contraia o glúteo no ponto final e retorne.'], form_tips: ['O movimento deve ser do quadril, não do joelho.'], common_mistakes: ['Usar amplitude excessiva arqueando a lombar.'], variations: ['Kick Back no Chão', 'Hip Extension na Máquina'], substitutes: ['Hip Thrust com Barra', 'Elevação Pélvica'] },
  // CARDIO
  { name: 'Polichinelo', category: 'cardio', primary_muscle: 'Corpo Todo', secondary_muscles: ['Cardiorrespiratório'], equipment: 'Peso corporal', difficulty: 'iniciante', animation_url: G.pc, instructions: 'Salte abrindo pernas e braços simultaneamente. Mantenha ritmo constante.', steps: ['Fique em pé com pés juntos e braços ao lado.', 'Salte abrindo as pernas e levando os braços acima da cabeça.', 'Salte de volta à posição inicial.', 'Repita em ritmo constante.'], form_tips: ['Aterrissse com joelhos levemente flexionados.'], common_mistakes: ['Aterrissar com joelhos travados.'], variations: ['Polichinelo com Agachamento'], substitutes: ['Corrida Estacionária', 'Pular Corda'] },
  { name: 'Burpee', category: 'cardio', primary_muscle: 'Corpo Todo', secondary_muscles: ['Cardiorrespiratório'], equipment: 'Peso corporal', difficulty: 'avancado', animation_url: G.bu, instructions: 'Flexão + salto. Movimento explosivo. Um dos melhores para condicionamento.', steps: ['Fique em pé.', 'Agache e apoie as mãos no chão.', 'Salte os pés para trás até a posição de flexão.', 'Faça uma flexão.', 'Salte os pés de volta para perto das mãos.', 'Salte para cima com os braços acima da cabeça.'], form_tips: ['Mantenha o core contraído.'], common_mistakes: ['Quadril caindo na posição de flexão.'], variations: ['Burpee sem Flexão', 'Burpee com Pull Up'], substitutes: ['Mountain Climber', 'Agachamento com Salto'] },
  { name: 'Corrida Estacionária', category: 'cardio', primary_muscle: 'Cardiorrespiratório', secondary_muscles: [], equipment: 'Peso corporal', difficulty: 'iniciante', animation_url: G.pc, instructions: 'Corra no lugar elevando os joelhos acima da linha do quadril.', steps: ['Fique em pé com joelhos levemente flexionados.', 'Eleve um joelho acima da linha do quadril.', 'Alterne rapidamente as pernas mantendo o ritmo.'], form_tips: ['Mantenha uma postura ereta.'], common_mistakes: ['Joelhos não atingindo a altura do quadril.'], variations: ['High Knees com Resistência'], substitutes: ['Polichinelo', 'Pular Corda'] },
  { name: 'Pular Corda', category: 'cardio', primary_muscle: 'Cardiorrespiratório', secondary_muscles: ['Panturrilha'], equipment: 'Corda', difficulty: 'iniciante', animation_url: G.pc, instructions: 'Saltos baixos e rápidos. Punhos fazem o movimento circular.', steps: ['Segure as alças da corda ao lado do corpo.', 'Dê um salto leve e passe a corda por baixo dos pés.', 'Aterrissse na ponta dos pés.', 'Mantenha os saltos baixos e consistentes.'], form_tips: ['O movimento circular vem dos punhos.'], common_mistakes: ['Saltos muito altos.'], variations: ['Pular Corda Duplo'], substitutes: ['Polichinelo', 'Corrida Estacionária'] },
  { name: 'Agachamento com Salto', category: 'cardio', primary_muscle: 'Quadríceps', secondary_muscles: ['Glúteos', 'Cardiorrespiratório'], equipment: 'Peso corporal', difficulty: 'intermediario', animation_url: G.sq, instructions: 'Agache e salte explosivamente. Alta demanda cardiovascular e muscular.', steps: ['Pés na largura dos ombros.', 'Desça em agachamento até as coxas ficarem paralelas.', 'Salte explosivamente para cima.', 'Aterrissse com joelhos levemente flexionados.'], form_tips: ['Aterrisagem macia.'], common_mistakes: ['Joelhos colapsando na aterrissagem.'], variations: ['Box Jump'], substitutes: ['Agachamento Livre', 'Burpee'] },
  { name: 'Sprint', category: 'cardio', primary_muscle: 'Cardiorrespiratório', secondary_muscles: ['Quadríceps', 'Glúteos'], equipment: 'Peso corporal', difficulty: 'intermediario', animation_url: G.pc, instructions: 'Corrida em alta velocidade por intervalos curtos. HIIT eficiente.', steps: ['Comece de pé ou com leve trote.', 'Acelere progressivamente até a velocidade máxima.', 'Mantenha a velocidade pelo tempo do intervalo.', 'Reduza a velocidade para recuperação ativa.'], form_tips: ['Braços em 90° e movimento para frente.'], common_mistakes: ['Não aquecer adequadamente antes.'], variations: ['HIIT na Esteira', 'Tiro em Ladeira'], substitutes: ['Agachamento com Salto', 'Burpee'] },
];

async function main() {
  console.log('Adicionando colunas se necessário...');
  try {
    await doSQL('ALTER TABLE exercise_library ADD COLUMN IF NOT EXISTS steps jsonb, ADD COLUMN IF NOT EXISTS form_tips jsonb, ADD COLUMN IF NOT EXISTS common_mistakes jsonb, ADD COLUMN IF NOT EXISTS variations jsonb, ADD COLUMN IF NOT EXISTS substitutes jsonb, ADD COLUMN IF NOT EXISTS animation_url text');
    console.log('Colunas OK.');
  } catch (e) { console.warn('Colunas (ok se já existirem):', e.message); }

  console.log('Limpando tabela...');
  await doSQL('DELETE FROM exercise_library');
  console.log('Tabela limpa.');

  let total = 0;
  for (let i = 0; i < EX.length; i += 20) {
    const batch = EX.slice(i, i + 20);
    await doREST('POST', 'exercise_library', batch);
    total += batch.length;
    console.log(`Inseridos: ${total}/${EX.length}`);
  }
  console.log(`\n✓ ${total} exercícios inseridos com sucesso!`);
}

main().catch(e => { console.error('ERRO FATAL:', e.message); process.exit(1); });
