import pg from 'pg';

const client = new pg.Client({
  host: 'db.fugztekwkpmambvcyrmm.supabase.co',
  port: 5432, database: 'postgres', user: 'postgres',
  password: process.env.DB_PASS,
  ssl: { rejectUnauthorized: false },
});

const GIF = {
  supino_reto:        'https://static.exercisedb.dev/media/EIeI8Vf.gif',
  supino_inclinado:   'https://static.exercisedb.dev/media/3TZduzM.gif',
  supino_declinado:   'https://static.exercisedb.dev/media/GrO65fd.gif',
  supino_db:          'https://static.exercisedb.dev/media/2vYapFl.gif',
  crucifixo:          'https://static.exercisedb.dev/media/1PLE8e9.gif',
  cross_over:         'https://static.exercisedb.dev/media/0CXGHya.gif',
  flexao:             'https://static.exercisedb.dev/media/0V2YQjW.gif',
  dead:               'https://static.exercisedb.dev/media/ila4NZS.gif',
  pull_up:            'https://static.exercisedb.dev/media/3_9Ib4w.gif',
  puxada_alta:        'https://static.exercisedb.dev/media/LEprlgG.gif',
  remada_barra:       'https://static.exercisedb.dev/media/eZyBC3j.gif',
  remada_uni:         'https://static.exercisedb.dev/media/C0MA9bC.gif',
  remada_db:          'https://static.exercisedb.dev/media/BJ0Hz5L.gif',
  remada_baixa:       'https://static.exercisedb.dev/media/A3P4O0R.gif',
  pullover:           'https://static.exercisedb.dev/media/0I0CmMl.gif',
  agach_livre:        'https://static.exercisedb.dev/media/DhMl549.gif',
  agach_hack:         'https://static.exercisedb.dev/media/5VCj6iH.gif',
  agach_sumo:         'https://static.exercisedb.dev/media/dzz6BiV.gif',
  agach_bulgaro:      'https://static.exercisedb.dev/media/jZi0Vj6.gif',
  leg_press:          'https://static.exercisedb.dev/media/10Z2DXU.gif',
  ext_joelho:         'https://static.exercisedb.dev/media/my33uHU.gif',
  mesa_flex:          'https://static.exercisedb.dev/media/17lJ1kr.gif',
  stiff:              'https://static.exercisedb.dev/media/5eLRITT.gif',
  afundo:             'https://static.exercisedb.dev/media/62Nw60O.gif',
  panturrilha:        'https://static.exercisedb.dev/media/bJYHBIN.gif',
  panturrilha_sent:   'https://static.exercisedb.dev/media/D2f6GxR.gif',
  hip_thrust:         'https://static.exercisedb.dev/media/qKBpF7I.gif',
  dev_barra:          'https://static.exercisedb.dev/media/kTbSH9h.gif',
  dev_db:             'https://static.exercisedb.dev/media/A6wtbuL.gif',
  dev_arnold:         'https://static.exercisedb.dev/media/Xy4jlWA.gif',
  elev_lat:           'https://static.exercisedb.dev/media/DsgkuIt.gif',
  elev_front:         'https://static.exercisedb.dev/media/3eGE2JC.gif',
  remada_alta:        'https://static.exercisedb.dev/media/83HoW9X.gif',
  face_pull:          'https://static.exercisedb.dev/media/gAwDzB3.gif',
  elev_post:          'https://static.exercisedb.dev/media/3mNAkfB.gif',
  rosca_barra:        'https://static.exercisedb.dev/media/25GPyDY.gif',
  rosca_alt:          'https://static.exercisedb.dev/media/Rn5zTiw.gif',
  rosca_martelo:      'https://static.exercisedb.dev/media/2sQGZ5b.gif',
  rosca_scott:        'https://static.exercisedb.dev/media/1V1gj1u.gif',
  rosca_conc:         'https://static.exercisedb.dev/media/1V1gj1u.gif',
  rosca_incl:         'https://static.exercisedb.dev/media/25GPyDY.gif',
  rosca_cabo:         'https://static.exercisedb.dev/media/dFRcMC5.gif',
  triceps_pulley:     'https://static.exercisedb.dev/media/gAwDzB3.gif',
  triceps_corda:      'https://static.exercisedb.dev/media/VKIFPTK.gif',
  triceps_frances:    'https://static.exercisedb.dev/media/2IxROQ1.gif',
  triceps_testa:      'https://static.exercisedb.dev/media/1TVoin7.gif',
  triceps_coice:      'https://static.exercisedb.dev/media/3T12T87.gif',
  mergulho_banco:     'https://static.exercisedb.dev/media/aWedzZX.gif',
  mergulho_par:       'https://static.exercisedb.dev/media/iqOdmMz.gif',
  abd_supra:          'https://static.exercisedb.dev/media/8xUv4J7.gif',
  prancha:            'https://static.exercisedb.dev/media/VBAWRPG.gif',
  elevacao_pernas:    'https://static.exercisedb.dev/media/B2Uyrd7.gif',
  mountain:           'https://static.exercisedb.dev/media/0MWdXj2.gif',
  abdutor:            'https://static.exercisedb.dev/media/CHpahtl.gif',
  polichinelo:        'https://static.exercisedb.dev/media/1g5bPpA.gif',
  burpee:             'https://static.exercisedb.dev/media/GvqfMDk.gif',
};

const exercises = [
  // ═══════════════════════════════════════════════════════════════
  // PEITO
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Supino Reto com Barra',
    category: 'peito', primary_muscle: 'Peitoral Maior',
    secondary_muscles: ['Tríceps', 'Deltóide Anterior'],
    equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.supino_reto,
    instructions: 'Deite no banco plano, segure a barra na largura dos ombros, desça ao peito e empurre de volta.',
    steps: [
      'Deite no banco plano com os pés bem apoiados no chão.',
      'Posicione as mãos na barra um pouco mais afastadas que a largura dos ombros, pegada pronada.',
      'Retire a barra do suporte mantendo os braços estendidos acima do peito.',
      'Inspire e desça a barra de forma controlada até tocar levemente a linha inferior do peitoral.',
      'Empurre a barra para cima de forma explosiva até os braços ficarem quase estendidos.',
      'Expire ao subir e repita o movimento mantendo o controle.',
    ],
    form_tips: [
      'Mantenha os ombros retraídos e deprimidos (para baixo e para trás) durante todo o exercício.',
      'Pés totalmente apoiados no chão — nunca cruze as pernas ou levante os pés.',
      'Mantenha um leve arco lombar natural; não force um arco exagerado.',
    ],
    common_mistakes: [
      'Arquear excessivamente a lombar e levantar o quadril do banco.',
      'Descer a barra de forma descontrolada e quicá no peito.',
      'Abrir os cotovelos em ângulo de 90°, sobrecarregando o ombro — mantenha a 45-75°.',
    ],
    variations: ['Supino com Halteres', 'Supino Inclinado', 'Supino Declinado', 'Supino no Smith'],
    substitutes: ['Flexão de Braço', 'Cross Over', 'Crucifixo com Halteres'],
  },
  {
    name: 'Supino Inclinado com Barra',
    category: 'peito', primary_muscle: 'Peitoral Superior',
    secondary_muscles: ['Tríceps', 'Deltóide Anterior'],
    equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.supino_inclinado,
    instructions: 'Banco inclinado a 30-45°. Foco na parte superior do peitoral.',
    steps: [
      'Ajuste o banco a 30-45° de inclinação.',
      'Deite e posicione as mãos na barra na largura dos ombros ou um pouco mais.',
      'Retire a barra do suporte mantendo os braços estendidos.',
      'Desça a barra de forma controlada em direção à clavícula/peito superior.',
      'Empurre a barra para cima até os braços ficarem quase estendidos.',
      'Mantenha o controle em todo o movimento.',
    ],
    form_tips: [
      'Inclinação de 30° é mais eficiente — 45° ou mais transfere muito para o ombro.',
      'Retraia as escápulas contra o banco durante todo o movimento.',
      'Cotovelos ligeiramente mais fechados que no supino reto.',
    ],
    common_mistakes: [
      'Usar inclinação excessiva (acima de 45°), ativando mais ombro que peitoral superior.',
      'Descida rápida sem controle do excêntrico.',
      'Não retrair as escápulas, deixando os ombros instáveis.',
    ],
    variations: ['Supino Inclinado com Halteres', 'Crucifixo Inclinado', 'Flexão com Pés Elevados'],
    substitutes: ['Supino Reto com Barra', 'Desenvolvimento com Halteres'],
  },
  {
    name: 'Supino Declinado com Barra',
    category: 'peito', primary_muscle: 'Peitoral Inferior',
    secondary_muscles: ['Tríceps'], equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.supino_declinado,
    instructions: 'Banco declinado. Enfatiza a porção inferior do peitoral.',
    steps: [
      'Ajuste o banco em declinação (cabeça para baixo, pés presos).',
      'Posicione as mãos na barra ligeiramente mais abertas que os ombros.',
      'Desça a barra de forma controlada em direção ao abdômen superior.',
      'Empurre de volta até os braços ficarem estendidos.',
    ],
    form_tips: [
      'Mantenha a cabeça apoiada no banco — não levante durante o movimento.',
      'O movimento é mais curto que no supino reto, cuide para não prender a respiração.',
    ],
    common_mistakes: [
      'Levantar a cabeça do banco ao forçar o peso.',
      'Descer a barra rápido demais sem controle.',
    ],
    variations: ['Supino Declinado com Halteres', 'Mergulho nas Paralelas'],
    substitutes: ['Mergulho no Banco', 'Cross Over com Cabos Altos'],
  },
  {
    name: 'Supino Reto com Halteres',
    category: 'peito', primary_muscle: 'Peitoral Maior',
    secondary_muscles: ['Tríceps', 'Deltóide Anterior'],
    equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.supino_db,
    instructions: 'Maior amplitude de movimento que a barra. Mantenha os cotovelos a 45°.',
    steps: [
      'Sente no banco com os halteres apoiados nas coxas.',
      'Deite no banco usando as coxas para posicionar os halteres ao lado do peito.',
      'Pressione os halteres para cima até quase se tocarem, sem travar os cotovelos.',
      'Desça de forma controlada, permitindo um leve alongamento no peito.',
    ],
    form_tips: [
      'Os halteres permitem maior amplitude — aproveite o alongamento controlado na descida.',
      'Mantenha os pulsos neutros (alinhados com os antebraços), não deixe dobrar para trás.',
    ],
    common_mistakes: [
      'Deixar os halteres se tocarem no topo — perde tensão e risca cair.',
      'Descer demais os halteres, sobrecarregando o ombro.',
    ],
    variations: ['Supino Inclinado com Halteres', 'Crucifixo com Halteres'],
    substitutes: ['Supino Reto com Barra', 'Flexão de Braço'],
  },
  {
    name: 'Supino Inclinado com Halteres',
    category: 'peito', primary_muscle: 'Peitoral Superior',
    secondary_muscles: ['Tríceps'], equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.supino_inclinado,
    instructions: 'Banco a 30-45°. Desça os halteres até a linha do peito.',
    steps: [
      'Ajuste o banco a 30-45° de inclinação.',
      'Sente com os halteres nas coxas e use-as para posicioná-los ao lado do peito ao deitar.',
      'Pressione os halteres para cima com uma leve convergência.',
      'Desça de forma controlada com cotovelos em 45-75°.',
    ],
    form_tips: ['Inclinação de 30° ativa mais peitoral superior sem sobrecarregar o ombro.'],
    common_mistakes: ['Usar inclinação acima de 45°, transferindo esforço para o deltoide.'],
    variations: ['Supino Inclinado com Barra', 'Crucifixo Inclinado'],
    substitutes: ['Cross Over com Cabo Baixo', 'Supino Reto com Halteres'],
  },
  {
    name: 'Crucifixo Reto',
    category: 'peito', primary_muscle: 'Peitoral Maior',
    secondary_muscles: ['Deltóide Anterior'], equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.crucifixo,
    instructions: 'Deite no banco, abra os braços em arco até sentir o alongamento no peitoral.',
    steps: [
      'Deite no banco plano com um halter em cada mão, braços estendidos acima do peito.',
      'Com uma leve flexão no cotovelo (não trave), abra os braços em arco para os lados.',
      'Desça até sentir um bom alongamento no peitoral (não force além do conforto).',
      'Contraia o peitoral e retorne ao ponto inicial em arco.',
    ],
    form_tips: [
      'Mantenha uma leve flexão nos cotovelos durante todo o movimento.',
      'O peso deve ser consideravelmente menor que no supino — é um exercício de isolamento.',
    ],
    common_mistakes: [
      'Fletir muito os cotovelos, transformando em um supino.',
      'Descer os halteres muito abaixo do nível do banco, sobrecarregando a articulação do ombro.',
    ],
    variations: ['Crucifixo Inclinado', 'Cross Over', 'Pec Deck'],
    substitutes: ['Cross Over', 'Supino com Halteres'],
  },
  {
    name: 'Crucifixo Inclinado',
    category: 'peito', primary_muscle: 'Peitoral Superior',
    secondary_muscles: ['Deltóide Anterior'], equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.crucifixo,
    instructions: 'Banco inclinado. Isola melhor a parte superior do peitoral.',
    steps: [
      'Ajuste o banco a 30°.',
      'Deite com os halteres estendidos acima do peito.',
      'Abra os braços em arco para os lados com leve flexão no cotovelo.',
      'Retorne ao ponto inicial contraindo o peitoral superior.',
    ],
    form_tips: ['Inclinação de 30° é ideal para ativar o peitoral clavicular sem virar um exercício de ombro.'],
    common_mistakes: ['Colocar inclinação muito alta — acima de 45° vira elevação de ombros.'],
    variations: ['Crucifixo Reto', 'Cross Over com Cabo Baixo'],
    substitutes: ['Supino Inclinado', 'Cross Over'],
  },
  {
    name: 'Cross Over',
    category: 'peito', primary_muscle: 'Peitoral Maior',
    secondary_muscles: ['Deltóide Anterior'], equipment: 'Cabo', difficulty: 'iniciante',
    animation_url: GIF.cross_over,
    instructions: 'Puxe os cabos em arco frente ao corpo. Contraia o peitoral na posição final.',
    steps: [
      'Posicione-se no centro da máquina de cabo com as polias em posição alta.',
      'Segure as alças com os braços abertos, pé dominante levemente à frente.',
      'Incline o tronco levemente para frente.',
      'Puxe as alças em arco convergindo as mãos na frente do corpo.',
      'Contraia o peitoral no ponto final e retorne controlando o excêntrico.',
    ],
    form_tips: [
      'As polias altas ativam mais o peitoral inferior; polias baixas, o superior.',
      'Mantenha os cotovelos levemente flexionados durante todo o movimento.',
    ],
    common_mistakes: [
      'Dobrar excessivamente os cotovelos, transformando em um supino.',
      'Não contrair o peitoral no ponto final do movimento.',
    ],
    variations: ['Cross Over Baixo (polia baixa)', 'Cross Over Médio (polia na altura do ombro)'],
    substitutes: ['Crucifixo com Halteres', 'Pec Deck'],
  },
  {
    name: 'Flexão de Braço',
    category: 'peito', primary_muscle: 'Peitoral Maior',
    secondary_muscles: ['Tríceps', 'Deltóide Anterior'],
    equipment: 'Peso corporal', difficulty: 'iniciante',
    animation_url: GIF.flexao,
    instructions: 'Mãos na largura dos ombros. Desça até o peito quase tocar o chão.',
    steps: [
      'Apoie as mãos no chão na largura dos ombros, dedos apontando para frente.',
      'Estenda os braços e apoie os dedos dos pés, mantendo o corpo em linha reta.',
      'Contraia o abdômen e os glúteos para estabilizar.',
      'Desça o corpo de forma controlada até o peito quase tocar o chão.',
      'Empurre de volta à posição inicial.',
    ],
    form_tips: [
      'Mantenha o corpo completamente reto — não deixe o quadril afundar ou subir.',
      'O pescoço deve estar neutro — olhe para o chão levemente à frente das mãos.',
    ],
    common_mistakes: [
      'Quadril caindo ou subindo (perda de alinhamento do corpo).',
      'Não descer até a amplitude completa.',
      'Cotovelos muito abertos (mais de 90°) sobrecarregam o ombro.',
    ],
    variations: ['Flexão Fechada (tríceps)', 'Flexão com Pés Elevados', 'Flexão Diamante', 'Flexão Inclinada'],
    substitutes: ['Supino Reto', 'Mergulho entre Bancos'],
  },
  {
    name: 'Flexão com Pés Elevados',
    category: 'peito', primary_muscle: 'Peitoral Superior',
    secondary_muscles: ['Tríceps', 'Deltóide Anterior'],
    equipment: 'Peso corporal', difficulty: 'intermediario',
    animation_url: GIF.flexao,
    instructions: 'Pés elevados para maior ativação da parte superior do peitoral.',
    steps: [
      'Posicione os pés em um banco ou superfície elevada.',
      'Apoie as mãos no chão na largura dos ombros.',
      'Desça o peito em direção ao chão de forma controlada.',
      'Empurre de volta mantendo o corpo reto.',
    ],
    form_tips: ['Quanto maior a elevação dos pés, maior a ativação do peitoral superior.'],
    common_mistakes: ['Deixar o quadril subir em vez de manter o corpo reto.'],
    variations: ['Flexão de Braço Padrão', 'Flexão Inclinada (mãos elevadas)'],
    substitutes: ['Supino Inclinado', 'Crucifixo Inclinado'],
  },
  {
    name: 'Mergulho entre Bancos',
    category: 'peito', primary_muscle: 'Peitoral Inferior',
    secondary_muscles: ['Tríceps'], equipment: 'Peso corporal', difficulty: 'iniciante',
    animation_url: GIF.mergulho_banco,
    instructions: 'Incline o corpo para frente para focar no peitoral inferior.',
    steps: [
      'Apoie as mãos em um banco atrás, pés em outro banco à frente (ou no chão).',
      'Incline o tronco ligeiramente para frente para ativar mais o peitoral.',
      'Desça flexionando os cotovelos até os braços ficarem a 90°.',
      'Empurre de volta à posição inicial.',
    ],
    form_tips: ['Quanto mais inclinado o tronco para frente, mais peitoral. Tronco ereto = mais tríceps.'],
    common_mistakes: ['Descer além de 90° nos cotovelos, sobrecarregando o ombro.'],
    variations: ['Mergulho nas Paralelas', 'Mergulho com Peso'],
    substitutes: ['Cross Over com Cabo Alto', 'Supino Declinado'],
  },

  // ═══════════════════════════════════════════════════════════════
  // COSTAS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Levantamento Terra',
    category: 'costas', primary_muscle: 'Eretores da Espinha',
    secondary_muscles: ['Glúteos', 'Isquiotibiais', 'Trapézio'],
    equipment: 'Barra', difficulty: 'avancado',
    animation_url: GIF.dead,
    instructions: 'Pés na largura do quadril, barra sobre os pés. Empurre o chão e mantenha as costas retas.',
    steps: [
      'Posicione os pés na largura do quadril com a barra sobre a metade dos pés.',
      'Agache para pegar a barra com pegada pronada ou mista, um pouco mais afastada que os pés.',
      'Posicione as escápulas acima da barra, costas retas (não arredondadas).',
      'Inspire fundo, pressione o abdômen (manobra de Valsalva) e empurre o chão.',
      'Mantenha a barra próxima ao corpo durante a subida — quase roçando as pernas.',
      'Na posição final, empurre os quadris para frente e estenda completamente.',
    ],
    form_tips: [
      'Antes de levantar, "quebre o chão" com os pés — isso ativa os glúteos e a cadeia posterior.',
      'Mantenha a barra o mais próximo do corpo possível — afastar sobrecarrega a lombar.',
      'Olhe para frente e um pouco para baixo — não olhe para o teto.',
    ],
    common_mistakes: [
      'Arredondar a lombar durante o levantamento — alto risco de lesão.',
      'Deixar os joelhos colapsarem para dentro na saída do chão.',
      'Puxar com as costas em vez de empurrar com as pernas.',
    ],
    variations: ['Levantamento Terra Sumô', 'Levantamento Terra Romeno (Stiff)', 'Levantamento Terra Unilateral'],
    substitutes: ['Remada Curvada com Barra', 'Stiff com Halteres'],
  },
  {
    name: 'Barra Fixa',
    category: 'costas', primary_muscle: 'Grande Dorsal',
    secondary_muscles: ['Bíceps', 'Rombóides'],
    equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.pull_up,
    instructions: 'Pegada pronada, largura maior que os ombros. Puxe até o queixo ultrapassar a barra.',
    steps: [
      'Segure a barra com pegada pronada, mãos um pouco mais afastadas que os ombros.',
      'Parta de braços completamente estendidos (posição morta).',
      'Retraia as escápulas e inicie o movimento puxando os cotovelos em direção aos quadris.',
      'Suba até o queixo ultrapassar a barra ou o peito tocar próximo a ela.',
      'Desça de forma controlada até a extensão completa.',
    ],
    form_tips: [
      'Inicie o movimento retraindo as escápulas — isso ativa o dorsal desde o início.',
      'Evite balançar o corpo (kipping) em treinos de força/hipertrofia.',
    ],
    common_mistakes: [
      'Não descer completamente (amplitude parcial).',
      'Usar impulso do corpo em vez de força muscular.',
      'Encolher os ombros na fase de baixo, sem ativação do dorsal.',
    ],
    variations: ['Barra Fixa com Pegada Supinada (chin-up)', 'Barra Fixa com Pegada Neutra', 'Barra Fixa com Peso'],
    substitutes: ['Puxada Alta', 'Remada Curvada com Barra'],
  },
  {
    name: 'Puxada Alta',
    category: 'costas', primary_muscle: 'Grande Dorsal',
    secondary_muscles: ['Bíceps', 'Rombóides'],
    equipment: 'Máquina', difficulty: 'iniciante',
    animation_url: GIF.puxada_alta,
    instructions: 'Puxe a barra até a clavícula, cotovelos apontando para baixo.',
    steps: [
      'Sente na máquina com as coxas presas sob o suporte e os pés no chão.',
      'Segure a barra com pegada pronada, mãos mais afastadas que os ombros.',
      'Incline o tronco levemente para trás (cerca de 15-20°).',
      'Puxe a barra em direção à clavícula/parte superior do peito, guiando com os cotovelos.',
      'Contraia o dorsal no ponto final e retorne controlando o excêntrico.',
    ],
    form_tips: [
      'Não puxe atrás da cabeça — sobrecarrega a cervical e o ombro.',
      'Foque em "puxar os cotovelos para baixo e para trás" em vez de puxar com as mãos.',
    ],
    common_mistakes: [
      'Puxar atrás da cabeça.',
      'Usar impulso do tronco para completar o movimento.',
      'Não controlar a fase excêntrica (subida da barra).',
    ],
    variations: ['Puxada com Pegada Fechada', 'Puxada Neutra', 'Puxada com Pegada Supinada'],
    substitutes: ['Barra Fixa', 'Remada Curvada'],
  },
  {
    name: 'Puxada Neutra',
    category: 'costas', primary_muscle: 'Grande Dorsal',
    secondary_muscles: ['Bíceps'], equipment: 'Máquina', difficulty: 'iniciante',
    animation_url: GIF.puxada_alta,
    instructions: 'Pegada paralela. Menor estresse no ombro, boa opção para iniciantes.',
    steps: [
      'Use a barra V (pegada neutra) no cabo.',
      'Sente com as coxas presas e o tronco levemente inclinado para trás.',
      'Puxe a barra em direção ao peito com os cotovelos apontando para baixo.',
      'Retorne controlando o movimento.',
    ],
    form_tips: ['A pegada neutra é a mais amigável para os ombros — boa opção para quem tem desconforto.'],
    common_mistakes: ['Inclinação excessiva do tronco, transformando em remada.'],
    variations: ['Puxada Alta', 'Barra Fixa Neutra'],
    substitutes: ['Puxada Alta', 'Remada Unilateral'],
  },
  {
    name: 'Remada Curvada com Barra',
    category: 'costas', primary_muscle: 'Grande Dorsal',
    secondary_muscles: ['Rombóides', 'Trapézio', 'Bíceps'],
    equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.remada_barra,
    instructions: 'Tronco a 45°, puxe a barra em direção ao umbigo. Mantenha as costas retas.',
    steps: [
      'Segure a barra na largura dos ombros com pegada pronada.',
      'Incline o tronco a aproximadamente 45° mantendo a coluna neutra.',
      'Com os joelhos levemente flexionados, puxe a barra em direção ao umbigo.',
      'Contraia as escápulas ao final do movimento.',
      'Retorne de forma controlada.',
    ],
    form_tips: [
      'Quanto mais paralelo ao chão o tronco, mais dorsal. Mais ereto, mais trapézio.',
      'Não curve a lombar — mantenha a coluna neutra durante todo o movimento.',
    ],
    common_mistakes: [
      'Arredondar as costas para levantar mais peso.',
      'Usar impulso do quadril (cheating) excessivo.',
      'Puxar para o peito em vez do abdômen, reduzindo ativação do dorsal.',
    ],
    variations: ['Remada Curvada com Halteres', 'Remada em T (T-bar row)', 'Remada Unilateral'],
    substitutes: ['Puxada Alta', 'Remada no Cabo'],
  },
  {
    name: 'Remada Unilateral com Halter',
    category: 'costas', primary_muscle: 'Grande Dorsal',
    secondary_muscles: ['Rombóides', 'Bíceps'],
    equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.remada_uni,
    instructions: 'Apoie um joelho no banco. Puxe o halter até o quadril.',
    steps: [
      'Apoie o joelho e a mão do mesmo lado no banco, pé oposto no chão.',
      'Segure o halter com o braço estendido perpendicularmente ao chão.',
      'Puxe o halter em direção ao quadril com o cotovelo apontando para o teto.',
      'No ponto final, retraia completamente a escápula.',
      'Retorne de forma controlada à posição inicial.',
    ],
    form_tips: [
      'Foque em "puxar o cotovelo para o teto" em vez de pensar no halter.',
      'Não gire o quadril para ajudar — mantenha o tronco paralelo ao chão.',
    ],
    common_mistakes: [
      'Rotacionar o quadril para completar o movimento.',
      'Não atingir a retração total da escápula no ponto final.',
    ],
    variations: ['Remada Curvada com Barra', 'Remada no Cabo Unilateral'],
    substitutes: ['Remada Curvada com Barra', 'Puxada Alta'],
  },
  {
    name: 'Remada Baixa no Cabo',
    category: 'costas', primary_muscle: 'Grande Dorsal',
    secondary_muscles: ['Rombóides', 'Trapézio'],
    equipment: 'Cabo', difficulty: 'iniciante',
    animation_url: GIF.remada_baixa,
    instructions: 'Puxe o cabo em direção ao abdômen, cotovelos próximos ao corpo.',
    steps: [
      'Sente na máquina com os pés apoiados na plataforma e os joelhos levemente flexionados.',
      'Segure a alça com os braços estendidos e o tronco levemente inclinado para frente.',
      'Puxe a alça em direção ao umbigo mantendo os cotovelos próximos ao corpo.',
      'Retraia as escápulas no ponto final e retorne controlando.',
    ],
    form_tips: ['Não balance o tronco para trás — o trabalho deve ser todo das costas.'],
    common_mistakes: ['Usar o tronco como alavanca (balanço excessivo).', 'Arredondar as costas na fase de extensão.'],
    variations: ['Remada com Barra de V', 'Remada com Corda', 'Remada Alta no Cabo'],
    substitutes: ['Remada Curvada com Barra', 'Remada Unilateral'],
  },
  {
    name: 'Remada com Halteres',
    category: 'costas', primary_muscle: 'Rombóides',
    secondary_muscles: ['Trapézio', 'Deltóide Posterior'],
    equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.remada_db,
    instructions: 'Incline o tronco. Puxe os halteres em direção ao quadril.',
    steps: [
      'Segure dois halteres e incline o tronco a 45-90°.',
      'Braços estendidos, costas neutras.',
      'Puxe os halteres simultaneamente em direção ao quadril.',
      'Contraia as escápulas e retorne.',
    ],
    form_tips: ['Pode ser feita com tronco mais horizontal para maior ativação do dorsal.'],
    common_mistakes: ['Não retrair as escápulas no ponto final.'],
    variations: ['Remada Curvada Unilateral', 'Remada Curvada com Barra'],
    substitutes: ['Remada Unilateral no Banco', 'Puxada Alta'],
  },
  {
    name: 'Encolhimento com Barra',
    category: 'costas', primary_muscle: 'Trapézio',
    secondary_muscles: ['Deltóide'], equipment: 'Barra', difficulty: 'iniciante',
    animation_url: GIF.remada_barra,
    instructions: 'Eleve os ombros em direção às orelhas. Não rode os ombros.',
    steps: [
      'Segure a barra com pegada pronada na largura dos ombros, braços estendidos.',
      'Eleve os ombros diretamente para cima em direção às orelhas.',
      'Mantenha no topo por 1 segundo contraindo o trapézio.',
      'Desça de forma controlada.',
    ],
    form_tips: ['Movimento estritamente vertical — não rode os ombros para frente ou para trás.'],
    common_mistakes: ['Rodar os ombros (movimento circular) — aumenta risco de lesão no ombro.'],
    variations: ['Encolhimento com Halteres', 'Encolhimento no Cabo', 'Encolhimento com Barra Atrás'],
    substitutes: ['Remada Alta', 'Face Pull'],
  },
  {
    name: 'Pull Over',
    category: 'costas', primary_muscle: 'Grande Dorsal',
    secondary_muscles: ['Peitoral', 'Tríceps'],
    equipment: 'Halteres', difficulty: 'intermediario',
    animation_url: GIF.pullover,
    instructions: 'Deite no banco, segure um halter com as duas mãos e desça atrás da cabeça.',
    steps: [
      'Deite transversalmente em um banco com apenas as escápulas apoiadas.',
      'Segure um halter com as duas mãos acima do peito.',
      'Com cotovelos levemente flexionados, desça o halter em arco atrás da cabeça.',
      'Retorne à posição inicial em arco, contraindo o dorsal.',
    ],
    form_tips: ['O quadril deve estar abaixo do nível do banco para maior amplitude.'],
    common_mistakes: ['Dobrar demais os cotovelos, transformando em tríceps francês.'],
    variations: ['Pull Over no Cabo', 'Pull Over na Máquina'],
    substitutes: ['Puxada Alta', 'Remada Curvada'],
  },

  // ═══════════════════════════════════════════════════════════════
  // PERNAS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Agachamento Livre',
    category: 'pernas', primary_muscle: 'Quadríceps',
    secondary_muscles: ['Glúteos', 'Isquiotibiais', 'Panturrilha'],
    equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.agach_livre,
    instructions: 'Pés na largura dos ombros, desça até as coxas ficarem paralelas ao chão.',
    steps: [
      'Posicione a barra na parte posterior dos trapézios (low bar) ou no alto das costas (high bar).',
      'Pés na largura dos ombros ou levemente mais afastados, pontas levemente para fora.',
      'Inspire fundo e pressione o abdômen (Valsalva).',
      'Inicie o movimento quebrando nos quadris e joelhos simultaneamente.',
      'Desça até as coxas ficarem paralelas ou abaixo do chão.',
      'Empurre o chão com os pés para subir, mantendo o tronco ereto.',
    ],
    form_tips: [
      'Joelhos devem acompanhar a direção dos pés — não colapse para dentro.',
      'Mantenha o peito erguido e a coluna neutra durante todo o movimento.',
      'Pressione os pés "para fora" do chão para ativar os glúteos.',
    ],
    common_mistakes: [
      'Joelhos colabeando para dentro (valgismo de joelho).',
      'Subir apenas com as costas (boa-manhã), indicando fraqueza nos quadríceps.',
      'Elevar os calcanhares do chão — indica encurtamento de tornozelo.',
    ],
    variations: ['Agachamento Sumô', 'Agachamento Hack', 'Agachamento Búlgaro', 'Agachamento Goblet'],
    substitutes: ['Leg Press', 'Cadeira Extensora', 'Afundo'],
  },
  {
    name: 'Agachamento Hack',
    category: 'pernas', primary_muscle: 'Quadríceps',
    secondary_muscles: ['Glúteos'], equipment: 'Máquina', difficulty: 'iniciante',
    animation_url: GIF.agach_hack,
    instructions: 'Ênfase na parte frontal da coxa. Pés a 45° para proteger os joelhos.',
    steps: [
      'Posicione-se na máquina com as costas apoiadas no encosto inclinado.',
      'Pés na plataforma na largura dos ombros, levemente para fora.',
      'Destrave a máquina e desça controlando até 90° nos joelhos.',
      'Empurre de volta sem travar os joelhos no topo.',
    ],
    form_tips: ['Pés mais baixos na plataforma = mais quadríceps. Pés mais altos = mais glúteos.'],
    common_mistakes: ['Levantar o calcanhar da plataforma.', 'Descer apenas parcialmente.'],
    variations: ['Agachamento Livre', 'Leg Press'],
    substitutes: ['Leg Press', 'Cadeira Extensora'],
  },
  {
    name: 'Agachamento Sumô',
    category: 'pernas', primary_muscle: 'Quadríceps',
    secondary_muscles: ['Glúteos', 'Adutores'],
    equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.agach_sumo,
    instructions: 'Pés mais afastados, pontas voltadas para fora. Ativa mais o glúteo e adutor.',
    steps: [
      'Pés bem afastados (mais que a largura dos ombros), pontas a 45° para fora.',
      'Barra nas costas (ou halter entre as pernas — Goblet).',
      'Inspire e desça mantendo o tronco mais ereto que no agachamento convencional.',
      'Desça até as coxas ficarem paralelas.',
      'Empurre de volta espalhando o chão com os pés.',
    ],
    form_tips: ['Mantenha os joelhos alinhados com os dedos dos pés durante todo o movimento.'],
    common_mistakes: ['Joelhos colapsando para dentro.', 'Inclinar excessivamente o tronco para frente.'],
    variations: ['Agachamento Livre', 'Agachamento Goblet Sumô'],
    substitutes: ['Leg Press com Pés Afastados', 'Cadeira de Abdutora'],
  },
  {
    name: 'Agachamento Búlgaro',
    category: 'pernas', primary_muscle: 'Quadríceps',
    secondary_muscles: ['Glúteos', 'Isquiotibiais'],
    equipment: 'Halteres', difficulty: 'avancado',
    animation_url: GIF.agach_bulgaro,
    instructions: 'Pé traseiro elevado. Excelente para força unilateral.',
    steps: [
      'Posicione o peito do pé traseiro em um banco atrás de você.',
      'Pé da frente a uma distância que permita 90° no joelho ao descer.',
      'Segure halteres em cada mão e desça em linha reta.',
      'Desça até o joelho traseiro quase tocar o chão.',
      'Empurre de volta com o pé da frente.',
    ],
    form_tips: [
      'O tronco pode inclinar levemente para frente — isso é normal.',
      'A distância do pé da frente ao banco determina o ângulo — ajuste até sentir conforto.',
    ],
    common_mistakes: [
      'Pé da frente muito próximo — joelho passa muito da ponta do pé.',
      'Perder o equilíbrio — comece com peso leve para adaptar.',
    ],
    variations: ['Afundo', 'Passada', 'Agachamento Unilateral'],
    substitutes: ['Afundo com Halteres', 'Leg Press Unilateral'],
  },
  {
    name: 'Leg Press 45°',
    category: 'pernas', primary_muscle: 'Quadríceps',
    secondary_muscles: ['Glúteos', 'Isquiotibiais'],
    equipment: 'Máquina', difficulty: 'iniciante',
    animation_url: GIF.leg_press,
    instructions: 'Pés na largura dos ombros. Desça até 90° nos joelhos.',
    steps: [
      'Sente na máquina com as costas e glúteos totalmente apoiados.',
      'Posicione os pés na plataforma na largura dos ombros.',
      'Destrave e desça controlando até os joelhos formarem 90°.',
      'Empurre de volta sem travar os joelhos no topo.',
    ],
    form_tips: [
      'Não deixe os glúteos saírem do assento — isso sobrecarrega a lombar.',
      'Pés mais altos na plataforma = mais glúteos. Pés mais baixos = mais quadríceps.',
    ],
    common_mistakes: [
      'Joelhos colapsando para dentro.',
      'Bloquear totalmente os joelhos no topo (hiperestensão).',
      'Glúteos saindo do banco no final da descida.',
    ],
    variations: ['Leg Press com Pés Altos', 'Leg Press Unilateral', 'Leg Press Sumô'],
    substitutes: ['Agachamento Livre', 'Agachamento Hack'],
  },
  {
    name: 'Cadeira Extensora',
    category: 'pernas', primary_muscle: 'Quadríceps',
    secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante',
    animation_url: GIF.ext_joelho,
    instructions: 'Isola o quadríceps. Faça contração no ponto final do movimento.',
    steps: [
      'Ajuste o banco para que o joelho fique alinhado ao eixo da máquina.',
      'Sente com o dorso dos joelhos apoiados na borda do banco.',
      'Estenda as pernas até quase o bloqueio e contraia o quadríceps.',
      'Retorne de forma controlada — não deixe o peso cair.',
    ],
    form_tips: ['Faça uma pausa de 1 segundo no ponto de contração máxima.'],
    common_mistakes: ['Usar impulso do tronco para completar o movimento.', 'Não controlar a descida.'],
    variations: ['Cadeira Extensora Unilateral'],
    substitutes: ['Agachamento Hack', 'Leg Press'],
  },
  {
    name: 'Mesa Flexora',
    category: 'pernas', primary_muscle: 'Isquiotibiais',
    secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante',
    animation_url: GIF.mesa_flex,
    instructions: 'Curl de perna deitado. Foco nos isquiotibiais.',
    steps: [
      'Deite na máquina com o dorso dos tornozelos sob o cilindro móvel.',
      'Joelhos logo na borda do banco.',
      'Flexione os joelhos trazendo o cilindro em direção aos glúteos.',
      'Contraia os isquiotibiais no topo e retorne controlando.',
    ],
    form_tips: ['Não levante os quadris do banco para completar o movimento.'],
    common_mistakes: ['Levantar o quadril, usando lombar em vez de isquiotibiais.'],
    variations: ['Cadeira Flexora', 'Stiff', 'Flexão de Joelho com Cabo'],
    substitutes: ['Stiff', 'Cadeira Flexora'],
  },
  {
    name: 'Cadeira Flexora',
    category: 'pernas', primary_muscle: 'Isquiotibiais',
    secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante',
    animation_url: GIF.mesa_flex,
    instructions: 'Curl de perna sentado. Mais estresse no isquiotibial distal.',
    steps: [
      'Sente na máquina com o encosto ajustado para que os joelhos fiquem no eixo.',
      'Posicione os tornozelos sobre o cilindro.',
      'Flexione os joelhos trazendo os calcanhares para baixo.',
      'Retorne controlando o excêntrico.',
    ],
    form_tips: ['Sentado, o isquiotibial fica em maior alongamento — respeite a amplitude.'],
    common_mistakes: ['Velocidade excessiva na fase excêntrica.'],
    variations: ['Mesa Flexora', 'Nordic Curl'],
    substitutes: ['Mesa Flexora', 'Stiff'],
  },
  {
    name: 'Stiff',
    category: 'pernas', primary_muscle: 'Isquiotibiais',
    secondary_muscles: ['Glúteos', 'Eretores da Espinha'],
    equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.stiff,
    instructions: 'Pernas quase estendidas, desça a barra pela frente das pernas sentindo o alongamento.',
    steps: [
      'Segure a barra na largura do quadril, braços estendidos.',
      'Com uma leve flexão nos joelhos (não bloqueados), incline o tronco para frente.',
      'Desça a barra pela frente das pernas mantendo-a próxima ao corpo.',
      'Sinta o alongamento nos isquiotibiais.',
      'Contraia os glúteos e isquiotibiais para retornar à posição inicial.',
    ],
    form_tips: [
      'Diferente do levantamento terra: o movimento é iniciado pelo quadril, não pelos joelhos.',
      'Mantenha a coluna neutra — não arredonde as costas.',
    ],
    common_mistakes: [
      'Arredondar as costas para alcançar mais amplitude.',
      'Dobrar demais os joelhos, transformando em levantamento terra.',
    ],
    variations: ['Stiff com Halteres', 'Stiff Unilateral', 'Levantamento Terra Romeno'],
    substitutes: ['Mesa Flexora', 'Levantamento Terra'],
  },
  {
    name: 'Afundo',
    category: 'pernas', primary_muscle: 'Quadríceps',
    secondary_muscles: ['Glúteos', 'Isquiotibiais'],
    equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.afundo,
    instructions: 'Passo longo à frente, desça o joelho traseiro próximo ao chão.',
    steps: [
      'Fique em pé com os halteres nas mãos ao lado do corpo.',
      'Dê um passo longo à frente com uma perna.',
      'Desça o joelho traseiro em direção ao chão sem tocá-lo.',
      'O joelho da frente deve ficar sobre o tornozelo, não à frente.',
      'Empurre de volta à posição inicial e alterne as pernas.',
    ],
    form_tips: ['Mantenha o tronco ereto — não incline excessivamente para frente.'],
    common_mistakes: ['Joelho da frente ultrapassando muito a ponta do pé.', 'Passo muito curto.'],
    variations: ['Afundo Caminhando', 'Agachamento Búlgaro', 'Passada com Barra'],
    substitutes: ['Agachamento Livre', 'Leg Press'],
  },
  {
    name: 'Panturrilha em Pé',
    category: 'pernas', primary_muscle: 'Panturrilha',
    secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante',
    animation_url: GIF.panturrilha,
    instructions: 'Suba na ponta dos pés com amplitude completa. Faça a contração no topo.',
    steps: [
      'Posicione os ombros sob os apoios da máquina.',
      'Pés na borda da plataforma — calcanhares para fora.',
      'Desça os calcanhares para baixo para alongar a panturrilha.',
      'Suba na ponta dos pés o mais alto possível e contraia no topo.',
      'Retorne controlando a descida.',
    ],
    form_tips: [
      'Amplitude completa é crucial — um movimento parcial não ativa o gastrocnêmio completamente.',
      'Faça uma pausa de 1 segundo no topo e na descida.',
    ],
    common_mistakes: ['Movimento parcial (não desce o calcanhar completamente).', 'Velocidade excessiva.'],
    variations: ['Panturrilha Sentado', 'Panturrilha no Leg Press', 'Panturrilha Unilateral'],
    substitutes: ['Panturrilha Sentado', 'Panturrilha no Leg Press'],
  },
  {
    name: 'Panturrilha Sentado',
    category: 'pernas', primary_muscle: 'Panturrilha',
    secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante',
    animation_url: GIF.panturrilha_sent,
    instructions: 'Foca no músculo sóleo. Importante para o volume total da panturrilha.',
    steps: [
      'Sente na máquina com os joelhos a 90° sob o apoio.',
      'Pés na borda da plataforma.',
      'Desça os calcanhares e suba na ponta dos pés em amplitude completa.',
    ],
    form_tips: ['O sóleo só é ativado com o joelho flexionado — por isso este exercício é único.'],
    common_mistakes: ['Não usar amplitude completa.'],
    variations: ['Panturrilha em Pé'],
    substitutes: ['Panturrilha em Pé', 'Panturrilha no Leg Press'],
  },

  // ═══════════════════════════════════════════════════════════════
  // OMBROS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Desenvolvimento Militar com Barra',
    category: 'ombros', primary_muscle: 'Deltóide Anterior',
    secondary_muscles: ['Deltóide Medial', 'Tríceps', 'Trapézio'],
    equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.dev_barra,
    instructions: 'Empurre a barra acima da cabeça. Pode ser feito em pé ou sentado.',
    steps: [
      'Segure a barra na largura dos ombros, cotovelos à frente.',
      'A barra fica na altura dos ombros antes de empurrar.',
      'Empurre a barra diretamente para cima até os braços ficarem estendidos.',
      'Desça de forma controlada até os ombros.',
    ],
    form_tips: ['Em pé ativa mais o core; sentado permite maior carga com mais estabilidade.'],
    common_mistakes: ['Arquear excessivamente a lombar ao empurrar.'],
    variations: ['Desenvolvimento com Halteres', 'Desenvolvimento Arnold', 'Push Press'],
    substitutes: ['Desenvolvimento com Halteres', 'Elevação Lateral'],
  },
  {
    name: 'Desenvolvimento com Halteres',
    category: 'ombros', primary_muscle: 'Deltóide Anterior',
    secondary_muscles: ['Deltóide Medial', 'Tríceps'],
    equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.dev_db,
    instructions: 'Maior amplitude que com barra. Cotovelos a 90° na posição inicial.',
    steps: [
      'Sente em um banco com encosto ou fique em pé.',
      'Segure os halteres na altura dos ombros, cotovelos a 90°.',
      'Empurre os halteres para cima com uma leve convergência.',
      'Retorne controlando a descida.',
    ],
    form_tips: ['Permite maior amplitude e trabalho de estabilização dos ombros.'],
    common_mistakes: ['Inclinar o tronco para trás excessivamente.'],
    variations: ['Desenvolvimento Arnold', 'Desenvolvimento Militar'],
    substitutes: ['Desenvolvimento com Barra', 'Elevação Lateral'],
  },
  {
    name: 'Desenvolvimento Arnold',
    category: 'ombros', primary_muscle: 'Deltóide Anterior',
    secondary_muscles: ['Deltóide Medial', 'Tríceps'],
    equipment: 'Halteres', difficulty: 'intermediario',
    animation_url: GIF.dev_arnold,
    instructions: 'Inicie com palmas viradas para você e gire durante o movimento.',
    steps: [
      'Segure os halteres na frente do rosto com as palmas voltadas para você.',
      'Ao empurrar para cima, gire os pulsos para fora.',
      'No topo, as palmas devem estar voltadas para frente.',
      'Retorne revertendo a rotação.',
    ],
    form_tips: ['O movimento de rotação ativa os três feixes do deltóide.'],
    common_mistakes: ['Fazer a rotação muito rápida sem controle.'],
    variations: ['Desenvolvimento com Halteres', 'Desenvolvimento com Barra'],
    substitutes: ['Desenvolvimento com Halteres'],
  },
  {
    name: 'Elevação Lateral',
    category: 'ombros', primary_muscle: 'Deltóide Medial',
    secondary_muscles: [], equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.elev_lat,
    instructions: 'Eleve os braços lateralmente até a altura dos ombros. Leve inclinação no cotovelo.',
    steps: [
      'Fique em pé com os halteres ao lado do corpo.',
      'Com uma leve flexão nos cotovelos, eleve os braços lateralmente.',
      'Pare quando os braços estiverem paralelos ao chão (altura dos ombros).',
      'Desça de forma controlada.',
    ],
    form_tips: [
      'Leve o polegar levemente para baixo no topo (rotação interna) para maior ativação do deltóide medial.',
      'Use cargas leves — o deltóide medial é um músculo pequeno.',
    ],
    common_mistakes: [
      'Levantar acima dos ombros — sobrecarrega o trapézio.',
      'Usar impulso do corpo (balanço).',
    ],
    variations: ['Elevação Lateral no Cabo', 'Elevação Lateral Inclinada'],
    substitutes: ['Face Pull', 'Desenvolvimento com Halteres'],
  },
  {
    name: 'Elevação Frontal',
    category: 'ombros', primary_muscle: 'Deltóide Anterior',
    secondary_muscles: [], equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.elev_front,
    instructions: 'Eleve os braços à frente até a altura dos ombros. Controle a descida.',
    steps: [
      'Fique em pé com os halteres na frente das coxas.',
      'Eleve um braço (ou ambos) à frente até a altura dos ombros.',
      'Retorne de forma controlada.',
    ],
    form_tips: ['Mantenha o tronco estável — não balance para trás para ajudar.'],
    common_mistakes: ['Usar impulso do tronco.', 'Subir acima da linha dos ombros.'],
    variations: ['Elevação Frontal com Barra', 'Elevação Frontal no Cabo'],
    substitutes: ['Elevação Lateral', 'Desenvolvimento com Halteres'],
  },
  {
    name: 'Remada Alta',
    category: 'ombros', primary_muscle: 'Deltóide Medial',
    secondary_muscles: ['Trapézio', 'Bíceps'],
    equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.remada_alta,
    instructions: 'Puxe a barra até a altura do queixo, cotovelos acima da barra.',
    steps: [
      'Segure a barra com pegada pronada, mãos na largura dos ombros.',
      'Puxe a barra verticalmente até a altura do queixo.',
      'Cotovelos devem ficar acima da barra no topo.',
      'Retorne de forma controlada.',
    ],
    form_tips: ['Pegada mais aberta reduz o risco de impingimento do ombro.'],
    common_mistakes: ['Pegada muito fechada — aumenta risco de lesão no ombro.'],
    variations: ['Remada Alta com Halteres', 'Remada Alta no Cabo'],
    substitutes: ['Elevação Lateral', 'Face Pull'],
  },
  {
    name: 'Face Pull',
    category: 'ombros', primary_muscle: 'Deltóide Posterior',
    secondary_muscles: ['Rombóides', 'Trapézio'],
    equipment: 'Cabo', difficulty: 'iniciante',
    animation_url: GIF.face_pull,
    instructions: 'Puxe o cabo em direção ao rosto, cotovelos elevados. Rotação externa no final.',
    steps: [
      'Configure a polia na altura dos olhos com a corda.',
      'Segure a corda com os dois lados.',
      'Dê um passo para trás e incline levemente o corpo.',
      'Puxe a corda em direção ao rosto, separando as mãos ao chegar.',
      'Cotovelos devem ficar na altura dos ombros ou acima.',
      'Faça a rotação externa dos ombros no ponto final.',
    ],
    form_tips: [
      'É um dos melhores exercícios para saúde e estabilidade do ombro.',
      'Foque na rotação externa — não apenas puxe a corda.',
    ],
    common_mistakes: ['Cotovelos abaixo da linha dos ombros.', 'Não fazer a rotação externa.'],
    variations: ['Face Pull com Elástico', 'Voador Invertido com Halteres'],
    substitutes: ['Elevação Posterior com Halteres', 'Remada Alta'],
  },
  {
    name: 'Elevação Posterior com Halteres',
    category: 'ombros', primary_muscle: 'Deltóide Posterior',
    secondary_muscles: ['Rombóides'],
    equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.elev_post,
    instructions: 'Incline o tronco a 90°, eleve os halteres lateralmente com cotovelos levemente flexionados.',
    steps: [
      'Sente na borda de um banco e incline o tronco até ficar paralelo ao chão.',
      'Segure os halteres com uma leve flexão nos cotovelos.',
      'Eleve os halteres lateralmente até os braços ficarem paralelos ao chão.',
      'Retorne de forma controlada.',
    ],
    form_tips: ['Mantenha o tronco paralelo ao chão durante o movimento — não suba para ajudar.'],
    common_mistakes: ['Levantar o tronco para usar impulso.', 'Dobrar demais os cotovelos.'],
    variations: ['Face Pull', 'Voador Invertido na Máquina'],
    substitutes: ['Face Pull', 'Remada Alta'],
  },

  // ═══════════════════════════════════════════════════════════════
  // BÍCEPS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Rosca Direta com Barra',
    category: 'biceps', primary_muscle: 'Bíceps Braquial',
    secondary_muscles: ['Braquial'], equipment: 'Barra', difficulty: 'iniciante',
    animation_url: GIF.rosca_barra,
    instructions: 'Cotovelos fixos ao longo do corpo. Curl completo sem balançar o tronco.',
    steps: [
      'Fique em pé com a barra segura com pegada supinada na largura dos ombros.',
      'Cotovelos fixos ao lado do corpo.',
      'Flexione os cotovelos trazendo a barra em direção ao peito.',
      'Contraia o bíceps no topo e retorne de forma controlada.',
    ],
    form_tips: ['Os cotovelos são o eixo do movimento — não deixe-os avançar para frente.'],
    common_mistakes: ['Balançar o tronco para ajudar no levantamento.', 'Cotovelos se afastando do corpo.'],
    variations: ['Rosca com EZ Bar', 'Rosca Alternada com Halteres', 'Rosca no Cabo'],
    substitutes: ['Rosca Alternada', 'Rosca no Cabo'],
  },
  {
    name: 'Rosca Alternada com Halteres',
    category: 'biceps', primary_muscle: 'Bíceps Braquial',
    secondary_muscles: ['Braquial'], equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.rosca_alt,
    instructions: 'Um braço de cada vez, supinando o pulso durante o movimento.',
    steps: [
      'Fique em pé com os halteres ao lado do corpo, palmas voltadas para dentro.',
      'Flex ione um cotovelo trazendo o halter em direção ao ombro.',
      'Gire o pulso para cima (supinação) durante a subida.',
      'Retorne e repita com o outro braço.',
    ],
    form_tips: ['A supinação do pulso durante o movimento maximiza a ativação do bíceps.'],
    common_mistakes: ['Não supinar o pulso.', 'Balançar o tronco para ajudar.'],
    variations: ['Rosca Direta com Barra', 'Rosca Martelo'],
    substitutes: ['Rosca Direta', 'Rosca no Cabo'],
  },
  {
    name: 'Rosca Martelo',
    category: 'biceps', primary_muscle: 'Braquial',
    secondary_muscles: ['Bíceps Braquial'], equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.rosca_martelo,
    instructions: 'Pegada neutra (polegar para cima). Ativa mais o braquial e antebraço.',
    steps: [
      'Segure os halteres com pegada neutra (palmas voltadas para o corpo).',
      'Flexione os cotovelos alternadamente ou simultaneamente.',
      'Mantenha a pegada neutra durante todo o movimento.',
      'Retorne de forma controlada.',
    ],
    form_tips: ['Essa pegada ativa o braquial, que fica sob o bíceps e contribui para o volume do braço.'],
    common_mistakes: ['Girar o pulso para supinado durante o movimento.'],
    variations: ['Rosca Corda (no cabo)', 'Rosca Cross Body'],
    substitutes: ['Rosca Alternada', 'Rosca Direta'],
  },
  {
    name: 'Rosca Scott',
    category: 'biceps', primary_muscle: 'Bíceps Braquial',
    secondary_muscles: [], equipment: 'Barra/Halteres', difficulty: 'iniciante',
    animation_url: GIF.rosca_scott,
    instructions: 'Apoio do braço no banco Scott. Isola o bíceps eliminando trapaça.',
    steps: [
      'Ajuste o banco Scott à altura das axilas.',
      'Posicione os tríceps no apoio inclinado.',
      'Segure a barra EZ ou halteres com pegada supinada.',
      'Flexione os cotovelos contraindo o bíceps.',
      'Retorne de forma controlada até o alongamento completo.',
    ],
    form_tips: ['Não trave os cotovelos no final — mantenha leve tensão.'],
    common_mistakes: ['Levantar o tríceps do suporte para completar o movimento.'],
    variations: ['Rosca Concentrada', 'Rosca Direta'],
    substitutes: ['Rosca Concentrada', 'Rosca no Cabo'],
  },
  {
    name: 'Rosca Concentrada',
    category: 'biceps', primary_muscle: 'Bíceps Braquial',
    secondary_muscles: [], equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.rosca_conc,
    instructions: 'Cotovelo apoiado na coxa. Máximo isolamento do bíceps.',
    steps: [
      'Sente no banco com as pernas abertas.',
      'Apoie a parte de trás do cotovelo na parte interna da coxa.',
      'Segure o halter e flexione o cotovelo em direção ao ombro.',
      'Retorne de forma controlada.',
    ],
    form_tips: ['A posição sentada e o apoio eliminam qualquer compensação.'],
    common_mistakes: ['Inclinar o tronco para ajudar no levantamento.'],
    variations: ['Rosca Scott', 'Rosca no Cabo'],
    substitutes: ['Rosca Scott', 'Rosca Direta'],
  },
  {
    name: 'Rosca Inclinada',
    category: 'biceps', primary_muscle: 'Bíceps Braquial',
    secondary_muscles: [], equipment: 'Halteres', difficulty: 'intermediario',
    animation_url: GIF.rosca_incl,
    instructions: 'Banco inclinado. Alongamento máximo do bíceps no ponto inferior.',
    steps: [
      'Ajuste o banco a 45-60°.',
      'Deite com os braços pendendo perpendicularmente ao chão.',
      'Flexione os cotovelos trazendo os halteres ao ombro.',
      'Retorne lentamente aproveitando o alongamento.',
    ],
    form_tips: ['A posição inclinada força um maior pré-alongamento do bíceps — ótimo para a cabeça longa.'],
    common_mistakes: ['Trazer os cotovelos para frente (perde o benefício do alongamento).'],
    variations: ['Rosca Alternada', 'Rosca Direta'],
    substitutes: ['Rosca Concentrada', 'Rosca no Cabo'],
  },
  {
    name: 'Rosca no Cabo',
    category: 'biceps', primary_muscle: 'Bíceps Braquial',
    secondary_muscles: [], equipment: 'Cabo', difficulty: 'iniciante',
    animation_url: GIF.rosca_cabo,
    instructions: 'Tensão constante ao longo do movimento. Ótimo para finalização.',
    steps: [
      'Configure a polia baixa com a barra reta ou EZ.',
      'Fique em pé e segure a barra com pegada supinada.',
      'Flexione os cotovelos trazendo a barra ao peito.',
      'Retorne controlando o excêntrico.',
    ],
    form_tips: ['O cabo mantém tensão constante, diferente do halter que perde tensão no topo.'],
    common_mistakes: ['Afastar os cotovelos do corpo.'],
    variations: ['Rosca no Cabo Unilateral', 'Rosca Martelo no Cabo'],
    substitutes: ['Rosca Direta com Barra', 'Rosca Alternada'],
  },

  // ═══════════════════════════════════════════════════════════════
  // TRÍCEPS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Tríceps Pulley',
    category: 'triceps', primary_muscle: 'Tríceps Braquial',
    secondary_muscles: [], equipment: 'Cabo', difficulty: 'iniciante',
    animation_url: GIF.triceps_pulley,
    instructions: 'Cotovelos fixos ao lado do corpo. Estenda completamente os braços.',
    steps: [
      'Configure a polia alta com a barra reta ou V.',
      'Segure a barra com pegada pronada, cotovelos próximos ao corpo.',
      'Estenda os cotovelos empurrando a barra para baixo.',
      'Contraia o tríceps no ponto final e retorne controlando.',
    ],
    form_tips: ['Os cotovelos são o eixo — não deixe-os se mover.'],
    common_mistakes: ['Cotovelos se afastando do corpo.', 'Inclinar o tronco para usar mais peso.'],
    variations: ['Tríceps Corda', 'Tríceps com Barra V', 'Tríceps Unilateral'],
    substitutes: ['Tríceps Francês', 'Tríceps Testa'],
  },
  {
    name: 'Tríceps Corda no Cabo',
    category: 'triceps', primary_muscle: 'Tríceps Braquial',
    secondary_muscles: [], equipment: 'Cabo', difficulty: 'iniciante',
    animation_url: GIF.triceps_corda,
    instructions: 'Abra a corda no final do movimento para maior amplitude.',
    steps: [
      'Configure a polia alta com a corda dupla.',
      'Segure a corda e posicione os cotovelos próximos ao corpo.',
      'Empurre para baixo e separe os lados da corda no ponto final.',
      'Retorne controlando o excêntrico.',
    ],
    form_tips: ['Separar a corda no final aumenta a contração da cabeça lateral do tríceps.'],
    common_mistakes: ['Não separar a corda no final.', 'Cotovelos se movendo.'],
    variations: ['Tríceps Pulley (barra)', 'Tríceps Overhead com Corda'],
    substitutes: ['Tríceps Pulley', 'Tríceps Testa'],
  },
  {
    name: 'Tríceps Francês',
    category: 'triceps', primary_muscle: 'Tríceps Braquial',
    secondary_muscles: [], equipment: 'Halteres/Barra', difficulty: 'intermediario',
    animation_url: GIF.triceps_frances,
    instructions: 'Deite ou sente. Desça o peso atrás da cabeça, cotovelos apontando para cima.',
    steps: [
      'Deite no banco ou sente, segurando um halter com os dois braços estendidos acima.',
      'Cotovelos apontando para cima, fixos.',
      'Desça o peso atrás da cabeça flexionando os cotovelos.',
      'Estenda de volta à posição inicial.',
    ],
    form_tips: ['Mantém os cotovelos apontando para o teto — não abra para os lados.'],
    common_mistakes: ['Cotovelos se abrindo excessivamente.'],
    variations: ['Tríceps Testa', 'Tríceps Overhead no Cabo'],
    substitutes: ['Tríceps Testa', 'Tríceps Pulley'],
  },
  {
    name: 'Tríceps Testa',
    category: 'triceps', primary_muscle: 'Tríceps Braquial',
    secondary_muscles: [], equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.triceps_testa,
    instructions: 'Deite no banco. Desça a barra em direção à testa com cotovelos fixos.',
    steps: [
      'Deite no banco com a barra EZ ou reta acima do peito.',
      'Cotovelos a 90° do tronco, apontando para cima.',
      'Desça a barra em direção à testa ou à parte superior da cabeça.',
      'Estenda os cotovelos voltando à posição inicial.',
    ],
    form_tips: ['A barra EZ é mais confortável para os pulsos do que a barra reta.'],
    common_mistakes: ['Cotovelos se movendo para fora durante o movimento.'],
    variations: ['Tríceps Francês', 'Tríceps Testa no Cabo'],
    substitutes: ['Tríceps Francês', 'Tríceps Pulley'],
  },
  {
    name: 'Tríceps Coice',
    category: 'triceps', primary_muscle: 'Tríceps Braquial',
    secondary_muscles: [], equipment: 'Halteres', difficulty: 'iniciante',
    animation_url: GIF.triceps_coice,
    instructions: 'Incline o tronco, cotovelo fixo. Estenda o braço para trás.',
    steps: [
      'Incline o tronco a 45° (ou apoie uma mão no banco).',
      'Segure o halter com o cotovelo flexionado a 90°, junto ao corpo.',
      'Estenda o cotovelo para trás até o braço ficar paralelo ao chão.',
      'Contraia o tríceps e retorne.',
    ],
    form_tips: ['Mantenha o cotovelo bem próximo ao corpo e na mesma altura.'],
    common_mistakes: ['Cotovelo caindo durante o movimento.', 'Amplitude incompleta.'],
    variations: ['Tríceps Coice no Cabo'],
    substitutes: ['Tríceps Pulley', 'Tríceps Corda'],
  },
  {
    name: 'Mergulho no Banco',
    category: 'triceps', primary_muscle: 'Tríceps Braquial',
    secondary_muscles: ['Peitoral Inferior'],
    equipment: 'Peso corporal', difficulty: 'iniciante',
    animation_url: GIF.mergulho_banco,
    instructions: 'Mãos no banco atrás, pernas estendidas. Desça flexionando os cotovelos.',
    steps: [
      'Apoie as mãos em um banco com os dedos apontando para frente.',
      'Pernas estendidas à frente (ou joelhos flexionados para facilitar).',
      'Desça flexionando os cotovelos até os braços ficarem a 90°.',
      'Empurre de volta à posição inicial.',
    ],
    form_tips: ['Mantenha o tronco próximo ao banco para focar mais no tríceps.'],
    common_mistakes: ['Descer além de 90°, sobrecarregando o ombro.'],
    variations: ['Mergulho nas Paralelas', 'Mergulho com Peso'],
    substitutes: ['Tríceps Pulley', 'Tríceps Testa'],
  },
  {
    name: 'Mergulho nas Paralelas',
    category: 'triceps', primary_muscle: 'Tríceps Braquial',
    secondary_muscles: ['Peitoral'],
    equipment: 'Peso corporal', difficulty: 'intermediario',
    animation_url: GIF.mergulho_par,
    instructions: 'Tronco ereto para focar no tríceps. Cotovelos próximos ao corpo.',
    steps: [
      'Segure as paralelas e suspenda o corpo.',
      'Mantenha o tronco o mais ereto possível.',
      'Desça flexionando os cotovelos até os braços ficarem a 90°.',
      'Empurre de volta.',
    ],
    form_tips: ['Tronco ereto = tríceps. Tronco inclinado = peitoral.'],
    common_mistakes: ['Descer excessivamente sobrecarregando o ombro.'],
    variations: ['Mergulho com Peso', 'Mergulho no Banco'],
    substitutes: ['Tríceps Testa', 'Tríceps Pulley'],
  },

  // ═══════════════════════════════════════════════════════════════
  // ABDÔMEN
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Abdominal Supra',
    category: 'abdomen', primary_muscle: 'Reto Abdominal',
    secondary_muscles: ['Oblíquos'], equipment: 'Peso corporal', difficulty: 'iniciante',
    animation_url: GIF.abd_supra,
    instructions: 'Deite, joelhos flexionados. Suba apenas o suficiente para as escápulas saírem do chão.',
    steps: [
      'Deite de costas com os joelhos flexionados e pés apoiados no chão.',
      'Posicione as mãos atrás da cabeça sem entrelaçar os dedos.',
      'Expire e contraia o abdômen, elevando as escápulas do chão.',
      'Inspire e retorne lentamente sem apoiar a cabeça no chão entre as repetições.',
    ],
    form_tips: [
      'Não puxe o pescoço com as mãos — as mãos são apenas suporte.',
      'O movimento é curto — não precisa sentar completamente.',
    ],
    common_mistakes: ['Puxar o pescoço com as mãos.', 'Usar impulso em vez de contração.'],
    variations: ['Abdominal com Rotação', 'Abdominal no Cabo', 'Crunch Reverso'],
    substitutes: ['Prancha Abdominal', 'Abdominal no Cabo'],
  },
  {
    name: 'Abdominal Infra',
    category: 'abdomen', primary_muscle: 'Reto Abdominal Inferior',
    secondary_muscles: [], equipment: 'Peso corporal', difficulty: 'iniciante',
    animation_url: GIF.elevacao_pernas,
    instructions: 'Deite. Eleve os joelhos em direção ao peito controlando o movimento.',
    steps: [
      'Deite de costas com os braços ao lado do corpo.',
      'Eleve as pernas até ficarem perpendiculares ao chão (ou joelhos até o peito).',
      'Contraia o abdômen e retorne lentamente.',
    ],
    form_tips: ['Não use impulso — o movimento deve ser lento e controlado.'],
    common_mistakes: ['Deixar as costas arquearem durante a descida.'],
    variations: ['Elevação de Pernas', 'Abdominal Infra com Haltere'],
    substitutes: ['Abdominal Supra', 'Prancha'],
  },
  {
    name: 'Prancha Abdominal',
    category: 'abdomen', primary_muscle: 'Core',
    secondary_muscles: ['Oblíquos', 'Glúteos'],
    equipment: 'Peso corporal', difficulty: 'iniciante',
    animation_url: GIF.prancha,
    instructions: 'Apoio nos cotovelos e pés. Mantenha o corpo reto. Respire normalmente.',
    steps: [
      'Apoie os cotovelos no chão diretamente abaixo dos ombros.',
      'Estique as pernas e apoie as pontas dos pés.',
      'Contraia o abdômen, glúteos e quadríceps.',
      'Mantenha o corpo em linha reta — não deixe o quadril cair ou subir.',
      'Respire normalmente pelo tempo desejado.',
    ],
    form_tips: ['Imagine que está empurrando o chão com os cotovelos — isso ativa mais o core.'],
    common_mistakes: ['Quadril caindo (fraqueza no core).', 'Quadril subindo demais (facilitar).', 'Prender a respiração.'],
    variations: ['Prancha Lateral', 'Prancha com Pés Elevados', 'Prancha com Toque de Ombro'],
    substitutes: ['Abdominal Supra', 'Mountain Climber'],
  },
  {
    name: 'Prancha Lateral',
    category: 'abdomen', primary_muscle: 'Oblíquos',
    secondary_muscles: ['Core'], equipment: 'Peso corporal', difficulty: 'intermediario',
    animation_url: GIF.prancha,
    instructions: 'Apoio em um cotovelo e pé. Quadril elevado formando linha reta.',
    steps: [
      'Deite de lado e apoie o cotovelo abaixo do ombro.',
      'Eleve o quadril formando uma linha reta do ombro ao tornozelo.',
      'Mantenha a posição pelo tempo desejado.',
    ],
    form_tips: ['Não deixe o quadril cair ou rotar.'],
    common_mistakes: ['Quadril caindo para baixo.', 'Apoiar o pé incorretamente.'],
    variations: ['Prancha Lateral com Elevação de Quadril'],
    substitutes: ['Prancha Abdominal', 'Abdominal com Rotação'],
  },
  {
    name: 'Abdominal com Rotação',
    category: 'abdomen', primary_muscle: 'Oblíquos',
    secondary_muscles: ['Reto Abdominal'],
    equipment: 'Peso corporal', difficulty: 'iniciante',
    animation_url: GIF.abd_supra,
    instructions: 'Suba e gire o tronco alternando os lados. Cotovelo em direção ao joelho oposto.',
    steps: [
      'Deite com joelhos flexionados.',
      'Mãos atrás da cabeça.',
      'Ao subir, gire o tronco levando o cotovelo direito ao joelho esquerdo.',
      'Alterne os lados de forma controlada.',
    ],
    form_tips: ['A rotação vem do tronco, não do pescoço.'],
    common_mistakes: ['Puxar o pescoço com as mãos.', 'Rotacionar apenas o cotovelo sem girar o tronco.'],
    variations: ['Russian Twist', 'Abdominal Supra'],
    substitutes: ['Prancha Lateral', 'Russian Twist'],
  },
  {
    name: 'Elevação de Pernas',
    category: 'abdomen', primary_muscle: 'Reto Abdominal Inferior',
    secondary_muscles: [], equipment: 'Peso corporal', difficulty: 'intermediario',
    animation_url: GIF.elevacao_pernas,
    instructions: 'Deite, pernas estendidas. Eleve até 90° e desça controlando.',
    steps: [
      'Deite com os braços ao lado do corpo ou segurando algo atrás.',
      'Pernas estendidas e unidas.',
      'Eleve as pernas até 90° (perpendicular ao chão).',
      'Desça lentamente sem tocar o chão.',
    ],
    form_tips: ['Quanto mais lenta a descida, maior o trabalho do abdômen inferior.'],
    common_mistakes: ['Deixar a lombar sair do chão durante a descida.'],
    variations: ['Elevação de Pernas na Barra', 'Abdominal Infra'],
    substitutes: ['Abdominal Infra', 'Prancha'],
  },
  {
    name: 'Abdominal no Cabo',
    category: 'abdomen', primary_muscle: 'Reto Abdominal',
    secondary_muscles: [], equipment: 'Cabo', difficulty: 'iniciante',
    animation_url: GIF.abd_supra,
    instructions: 'Ajoelhe-se de costas para o cabo. Flexione o tronco contraindo o abdômen.',
    steps: [
      'Configure a polia alta com a corda.',
      'Ajoelhe-se de frente para a máquina.',
      'Segure a corda atrás da cabeça.',
      'Flexione o tronco em direção ao chão contraindo o abdômen.',
      'Retorne controlando.',
    ],
    form_tips: ['O movimento vem do abdômen — não flexione os quadris.'],
    common_mistakes: ['Puxar com os braços em vez de contrair o abdômen.'],
    variations: ['Abdominal Supra', 'Abdominal com Roda'],
    substitutes: ['Abdominal Supra', 'Prancha'],
  },
  {
    name: 'Mountain Climber',
    category: 'abdomen', primary_muscle: 'Core',
    secondary_muscles: ['Oblíquos', 'Quadríceps'],
    equipment: 'Peso corporal', difficulty: 'intermediario',
    animation_url: GIF.mountain,
    instructions: 'Posição de flexão. Alterne puxando os joelhos em direção ao peito rapidamente.',
    steps: [
      'Comece na posição de flexão com os braços estendidos.',
      'Puxe o joelho direito em direção ao peito.',
      'Retorne e puxe o joelho esquerdo.',
      'Alterne em ritmo rápido.',
    ],
    form_tips: ['Mantenha o quadril baixo — não deixe subir durante o movimento.'],
    common_mistakes: ['Quadril elevado.', 'Ritmo muito lento (perde o componente cardiovascular).'],
    variations: ['Mountain Climber Lento (foco no core)', 'Mountain Climber Diagonal (oblíquos)'],
    substitutes: ['Prancha Abdominal', 'Burpee'],
  },

  // ═══════════════════════════════════════════════════════════════
  // GLÚTEOS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Hip Thrust com Barra',
    category: 'gluteos', primary_muscle: 'Glúteo Máximo',
    secondary_muscles: ['Isquiotibiais', 'Core'],
    equipment: 'Barra', difficulty: 'intermediario',
    animation_url: GIF.hip_thrust,
    instructions: 'Costas apoiadas no banco, barra no quadril. Empurre o quadril para cima contraindo o glúteo.',
    steps: [
      'Sente no chão com as costas encostadas na borda de um banco.',
      'Posicione a barra no dobramento do quadril com proteção (almofada).',
      'Pés apoiados no chão na largura dos ombros.',
      'Empurre o quadril para cima até o corpo ficar paralelo ao chão.',
      'Contraia o glúteo com força no topo por 1 segundo.',
      'Retorne de forma controlada.',
    ],
    form_tips: [
      'No ponto mais alto, o tronco e as coxas devem formar uma linha reta.',
      'Empurre os joelhos para fora durante o movimento para maior ativação do glúteo médio.',
    ],
    common_mistakes: [
      'Hiperextender a lombar no topo — o movimento deve ser do quadril.',
      'Pés muito próximos ou afastados dos glúteos.',
    ],
    variations: ['Hip Thrust Unilateral', 'Elevação Pélvica', 'Hip Thrust no Cabo'],
    substitutes: ['Elevação Pélvica', 'Agachamento Sumô'],
  },
  {
    name: 'Elevação Pélvica',
    category: 'gluteos', primary_muscle: 'Glúteo Máximo',
    secondary_muscles: ['Isquiotibiais'],
    equipment: 'Peso corporal', difficulty: 'iniciante',
    animation_url: GIF.hip_thrust,
    instructions: 'Deite, joelhos flexionados. Eleve o quadril contraindo o glúteo no topo.',
    steps: [
      'Deite de costas com os joelhos flexionados e pés no chão.',
      'Braços ao lado do corpo.',
      'Eleve o quadril contraindo o glúteo até o corpo formar uma linha reta.',
      'Retorne lentamente.',
    ],
    form_tips: ['Ative o glúteo antes de iniciar o movimento — "acorde" o músculo.'],
    common_mistakes: ['Não contrair o glúteo no topo.', 'Hiperextender a lombar.'],
    variations: ['Hip Thrust com Barra', 'Elevação Pélvica Unilateral'],
    substitutes: ['Hip Thrust', 'Agachamento Sumô'],
  },
  {
    name: 'Cadeira de Abdutora',
    category: 'gluteos', primary_muscle: 'Glúteo Médio',
    secondary_muscles: [], equipment: 'Máquina', difficulty: 'iniciante',
    animation_url: GIF.abdutor,
    instructions: 'Abra as pernas contra a resistência. Foco no glúteo médio e lateral.',
    steps: [
      'Sente na máquina com as pernas contra os apoios internos.',
      'Abra as pernas contra a resistência até a amplitude máxima confortável.',
      'Contraia o glúteo médio no ponto final.',
      'Retorne de forma controlada.',
    ],
    form_tips: ['Faça uma pausa de 1 segundo no ponto de maior abertura.'],
    common_mistakes: ['Não controlar a fase de retorno (excêntrico).'],
    variations: ['Abdução com Elástico', 'Elevação Lateral de Perna'],
    substitutes: ['Agachamento Sumô', 'Hip Thrust Unilateral'],
  },
  {
    name: 'Elevação de Quadril Unilateral',
    category: 'gluteos', primary_muscle: 'Glúteo Máximo',
    secondary_muscles: ['Core'],
    equipment: 'Peso corporal', difficulty: 'intermediario',
    animation_url: GIF.hip_thrust,
    instructions: 'Uma perna estendida. Maior ativação e desequilíbrio muscular corrigido.',
    steps: [
      'Deite de costas com um joelho flexionado e o outro estendido.',
      'Eleve o quadril usando apenas a perna apoiada.',
      'Mantenha a perna estendida paralela à outra.',
    ],
    form_tips: ['Excelente para corrigir desequilíbrios entre os dois glúteos.'],
    common_mistakes: ['Rotacionar o quadril para compensar fraqueza.'],
    variations: ['Hip Thrust Unilateral com Barra', 'Elevação Pélvica'],
    substitutes: ['Elevação Pélvica', 'Hip Thrust com Barra'],
  },
  {
    name: 'Agachamento com Faixa Elástica',
    category: 'gluteos', primary_muscle: 'Glúteo Máximo',
    secondary_muscles: ['Quadríceps', 'Glúteo Médio'],
    equipment: 'Faixa Elástica', difficulty: 'iniciante',
    animation_url: GIF.agach_livre,
    instructions: 'Faixa acima dos joelhos. Empurre os joelhos para fora durante o agachamento.',
    steps: [
      'Posicione a faixa elástica logo acima dos joelhos.',
      'Pés na largura dos ombros.',
      'Empurre os joelhos para fora contra a resistência da faixa ao descer.',
      'Mantenha a pressão na faixa durante todo o movimento.',
    ],
    form_tips: ['A faixa obriga ativação contínua do glúteo médio para manter os joelhos alinhados.'],
    common_mistakes: ['Deixar os joelhos colapsarem — se colapsam, a faixa está muito pesada.'],
    variations: ['Agachamento Livre', 'Hip Thrust com Faixa'],
    substitutes: ['Cadeira de Abdutora', 'Agachamento Sumô'],
  },
  {
    name: 'Stiff Unilateral',
    category: 'gluteos', primary_muscle: 'Glúteo Máximo',
    secondary_muscles: ['Isquiotibiais'],
    equipment: 'Halteres', difficulty: 'intermediario',
    animation_url: GIF.stiff,
    instructions: 'Uma perna de cada vez. Inclina o tronco enquanto eleva a perna traseira.',
    steps: [
      'Fique em pé com um halter na mão oposta ao lado de apoio.',
      'Incline o tronco para frente elevando a perna traseira.',
      'Mantenha a coluna neutra e a perna de apoio levemente flexionada.',
      'Retorne à posição inicial.',
    ],
    form_tips: ['Foque em "empurrar o calcanhar para o teto" com a perna livre.'],
    common_mistakes: ['Deixar o quadril girar (rotar) durante o movimento.'],
    variations: ['Stiff com Barra', 'Levantamento Terra Unilateral'],
    substitutes: ['Stiff', 'Hip Thrust Unilateral'],
  },
  {
    name: 'Kick Back no Cabo',
    category: 'gluteos', primary_muscle: 'Glúteo Máximo',
    secondary_muscles: [], equipment: 'Cabo', difficulty: 'iniciante',
    animation_url: GIF.face_pull,
    instructions: 'De frente para o cabo, empurre a perna para trás contraindo o glúteo.',
    steps: [
      'Prenda o cabo no tornozelo na polia baixa.',
      'Segure a máquina para apoio, levemente inclinado.',
      'Empurre a perna para trás mantendo o joelho levemente flexionado.',
      'Contraia o glúteo no ponto final e retorne.',
    ],
    form_tips: ['O movimento deve ser do quadril, não do joelho — não chute, empurre.'],
    common_mistakes: ['Usar amplitude excessiva arqueando a lombar.'],
    variations: ['Kick Back no Chão', 'Hip Extension na Máquina'],
    substitutes: ['Hip Thrust', 'Elevação Pélvica'],
  },

  // ═══════════════════════════════════════════════════════════════
  // CARDIO
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Polichinelo',
    category: 'cardio', primary_muscle: 'Corpo Todo',
    secondary_muscles: ['Cardiorrespiratório'],
    equipment: 'Peso corporal', difficulty: 'iniciante',
    animation_url: GIF.polichinelo,
    instructions: 'Salte abrindo pernas e braços simultaneamente. Mantenha ritmo constante.',
    steps: [
      'Fique em pé com os pés juntos e braços ao lado.',
      'Salte abrindo as pernas na largura dos ombros e levando os braços acima da cabeça.',
      'Salte de volta à posição inicial.',
      'Repita em ritmo constante.',
    ],
    form_tips: ['Aterrissse com os joelhos levemente flexionados para proteger as articulações.'],
    common_mistakes: ['Aterrissar com os joelhos travados.'],
    variations: ['Polichinelo com Agachamento', 'Polichinelo com Step'],
    substitutes: ['Corrida Estacionária', 'Pular Corda'],
  },
  {
    name: 'Burpee',
    category: 'cardio', primary_muscle: 'Corpo Todo',
    secondary_muscles: ['Cardiorrespiratório'],
    equipment: 'Peso corporal', difficulty: 'avancado',
    animation_url: GIF.burpee,
    instructions: 'Flexão + salto. Movimento explosivo. Um dos melhores para condicionamento.',
    steps: [
      'Fique em pé.',
      'Agache e apoie as mãos no chão.',
      'Salte os pés para trás até a posição de flexão.',
      'Faça uma flexão (opcional).',
      'Salte os pés de volta para perto das mãos.',
      'Salte para cima com os braços acima da cabeça.',
    ],
    form_tips: ['Mantenha o core contraído durante todo o movimento.'],
    common_mistakes: ['Quadril caindo na posição de flexão.', 'Não estender completamente no salto.'],
    variations: ['Burpee sem Flexão', 'Burpee com Pull Up'],
    substitutes: ['Mountain Climber', 'Agachamento com Salto'],
  },
  {
    name: 'Corrida Estacionária',
    category: 'cardio', primary_muscle: 'Cardiorrespiratório',
    secondary_muscles: [],
    equipment: 'Peso corporal', difficulty: 'iniciante',
    animation_url: GIF.polichinelo,
    instructions: 'Corra no lugar elevando os joelhos acima da linha do quadril.',
    steps: [
      'Fique em pé com os joelhos levemente flexionados.',
      'Eleve um joelho acima da linha do quadril enquanto o braço oposto sobe.',
      'Alterne rapidamente as pernas mantendo o ritmo.',
    ],
    form_tips: ['Mantenha uma postura ereta — não incline o tronco para frente.'],
    common_mistakes: ['Joelhos não atingindo a altura do quadril.'],
    variations: ['High Knees com Resistência', 'Polichinelo'],
    substitutes: ['Polichinelo', 'Pular Corda'],
  },
  {
    name: 'Pular Corda',
    category: 'cardio', primary_muscle: 'Cardiorrespiratório',
    secondary_muscles: ['Panturrilha', 'Coordenação'],
    equipment: 'Corda', difficulty: 'iniciante',
    animation_url: GIF.polichinelo,
    instructions: 'Saltos baixos e rápidos. Punhos fazem o movimento circular.',
    steps: [
      'Segure as alças da corda ao lado do corpo.',
      'Dê um salto leve e passe a corda por baixo dos pés.',
      'Aterrissse na ponta dos pés.',
      'Mantenha os saltos baixos e consistentes.',
    ],
    form_tips: ['O movimento circular vem dos punhos, não dos braços inteiros.'],
    common_mistakes: ['Saltos muito altos (cansa mais e reduz velocidade).'],
    variations: ['Pular Corda Duplo', 'Pular Corda com Alternância de Pés'],
    substitutes: ['Polichinelo', 'Corrida Estacionária'],
  },
  {
    name: 'Agachamento com Salto',
    category: 'cardio', primary_muscle: 'Quadríceps',
    secondary_muscles: ['Glúteos', 'Cardiorrespiratório'],
    equipment: 'Peso corporal', difficulty: 'intermediario',
    animation_url: GIF.agach_livre,
    instructions: 'Agache e salte explosivamente. Alta demanda cardiovascular e muscular.',
    steps: [
      'Pés na largura dos ombros.',
      'Desça em agachamento até as coxas ficarem paralelas.',
      'Salte explosivamente para cima estendendo completamente.',
      'Aterrissse com os joelhos levemente flexionados.',
    ],
    form_tips: ['Aterrisagem macia — não "bata" no chão com os pés.'],
    common_mistakes: ['Joelhos colapsando na aterrissagem.'],
    variations: ['Box Jump', 'Agachamento com Peso e Salto'],
    substitutes: ['Agachamento Livre', 'Burpee'],
  },
  {
    name: 'Sprint',
    category: 'cardio', primary_muscle: 'Cardiorrespiratório',
    secondary_muscles: ['Quadríceps', 'Glúteos'],
    equipment: 'Peso corporal', difficulty: 'intermediario',
    animation_url: GIF.polichinelo,
    instructions: 'Corrida em alta velocidade por intervalos curtos. HIIT eficiente.',
    steps: [
      'Comece de pé ou com leve trote.',
      'Acelere progressivamente até a velocidade máxima.',
      'Mantenha a velocidade pelo tempo do intervalo (10-30 segundos).',
      'Reduza a velocidade para recuperação ativa.',
    ],
    form_tips: ['Braços em 90° e movimento para frente — não cruzar o centro do corpo.'],
    common_mistakes: ['Não aquece adequadamente antes do sprint.'],
    variations: ['HIIT na Esteira', 'Tiro em Ladeira'],
    substitutes: ['Agachamento com Salto', 'Burpee'],
  },
];

async function run() {
  await client.connect();
  console.log('Conectado ao banco.');

  // Adicionar colunas novas se não existirem
  await client.query(`
    ALTER TABLE exercise_library
      ADD COLUMN IF NOT EXISTS steps jsonb,
      ADD COLUMN IF NOT EXISTS form_tips jsonb,
      ADD COLUMN IF NOT EXISTS common_mistakes jsonb,
      ADD COLUMN IF NOT EXISTS variations jsonb,
      ADD COLUMN IF NOT EXISTS substitutes jsonb;
  `);
  console.log('Colunas verificadas/criadas.');

  // Limpar tabela
  await client.query('TRUNCATE TABLE exercise_library RESTART IDENTITY CASCADE');
  console.log('Tabela limpa.');

  // Inserir exercícios
  let count = 0;
  for (const ex of exercises) {
    await client.query(`
      INSERT INTO exercise_library
        (name, category, primary_muscle, secondary_muscles, equipment, difficulty,
         instructions, animation_url, steps, form_tips, common_mistakes, variations, substitutes)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
    `, [
      ex.name, ex.category, ex.primary_muscle,
      ex.secondary_muscles || [],
      ex.equipment, ex.difficulty,
      ex.instructions || '',
      ex.animation_url || null,
      JSON.stringify(ex.steps || []),
      JSON.stringify(ex.form_tips || []),
      JSON.stringify(ex.common_mistakes || []),
      JSON.stringify(ex.variations || []),
      JSON.stringify(ex.substitutes || []),
    ]);
    count++;
  }

  console.log(`✓ ${count} exercícios inseridos com sucesso!`);
  await client.end();
}

run().catch(e => { console.error('Erro:', e.message); process.exit(1); });
